// Command observer is the CLI entry point for the SuperBased Observer.
//
// All capture/query/manage subcommands (scan, watch, init, uninstall, serve,
// doctor, status, tail, prune, cost, score, discover, patterns, learn,
// suggest, dashboard, metrics, summarize, export) are wired directly under
// the root. The legacy `observer observer ...` nesting is preserved as a
// hidden alias group so installed hooks and MCP registrations from earlier
// versions keep working without re-init.
package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/spf13/cobra"

	"github.com/marmutapp/superbased-observer/internal/adapter"
	"github.com/marmutapp/superbased-observer/internal/adapter/claudecode"
	"github.com/marmutapp/superbased-observer/internal/adapter/cline"
	"github.com/marmutapp/superbased-observer/internal/adapter/codex"
	"github.com/marmutapp/superbased-observer/internal/adapter/copilot"
	"github.com/marmutapp/superbased-observer/internal/adapter/openclaw"
	"github.com/marmutapp/superbased-observer/internal/adapter/opencode"
	"github.com/marmutapp/superbased-observer/internal/adapter/pi"
	"github.com/marmutapp/superbased-observer/internal/compression/indexing"
	"github.com/marmutapp/superbased-observer/internal/config"
	"github.com/marmutapp/superbased-observer/internal/db"
	"github.com/marmutapp/superbased-observer/internal/freshness"
	"github.com/marmutapp/superbased-observer/internal/platform/crossmount"
	"github.com/marmutapp/superbased-observer/internal/store"
	"github.com/marmutapp/superbased-observer/internal/watcher"
)

// version is stamped at build time via -ldflags="-X main.version=...".
var version = "dev"

func main() {
	if err := newRootCmd().Execute(); err != nil {
		// `observer run` forwards the wrapped command's exit code via exitErr;
		// everything else gets a generic non-zero exit (cobra already printed).
		var ec exitErr
		if errors.As(err, &ec) {
			os.Exit(int(ec))
		}
		os.Exit(1)
	}
}

func newRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:          "observer",
		Short:        "SuperBased Observer — unify AI coding tool activity",
		Long:         "Captures, normalizes, and analyzes tool call activity from AI coding assistants.\nSee README.md for a feature tour.",
		Version:      version,
		SilenceUsage: true,
	}
	for _, c := range observerSubcommands() {
		root.AddCommand(c)
	}
	root.AddCommand(newHookCmd())
	root.AddCommand(newProxyCmd())
	root.AddCommand(newRunCmd())
	root.AddCommand(newStartCmd())
	root.AddCommand(newObserverAliasCmd())
	return root
}

// observerSubcommands returns the full set of capture/query/manage commands.
// Each constructor returns a fresh *cobra.Command, so the slice can be
// regenerated by the alias group below without sharing state with the root.
func observerSubcommands() []*cobra.Command {
	return []*cobra.Command{
		newScanCmd(),
		newWatchCmd(),
		newInitCmd(),
		newUninstallCmd(),
		newServeCmd(),
		newDoctorCmd(),
		newStatusCmd(),
		newTailCmd(),
		newPruneCmd(),
		newCostCmd(),
		newScoreCmd(),
		newDiscoverCmd(),
		newPatternsCmd(),
		newLearnCmd(),
		newSuggestCmd(),
		newDashboardCmd(),
		newMetricsCmd(),
		newSummarizeCmd(),
		newExportCmd(),
		newBackfillCmd(),
	}
}

// newObserverAliasCmd preserves the deprecated `observer observer <sub>` form
// so existing hook registrations, MCP entries, and user scripts continue to
// work after the flatten. Hidden from --help; the canonical surface is the
// root.
func newObserverAliasCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:        "observer",
		Short:      "Deprecated alias group — use the top-level subcommands instead.",
		Hidden:     true,
		Deprecated: "subcommands have been promoted to the root (e.g. `observer scan` instead of `observer observer scan`).",
	}
	for _, c := range observerSubcommands() {
		cmd.AddCommand(c)
	}
	return cmd
}

func newScanCmd() *cobra.Command {
	var (
		configPath string
		force      bool
	)
	cmd := &cobra.Command{
		Use:   "scan",
		Short: "One-time backfill — parse all known session files",
		Long: `Walks every detected adapter's session files and ingests their
events. Default mode resumes from the saved parse cursor — fast, but
won't recover anything the live watcher dropped silently. Pass --force
to ignore the cursor and re-walk every file from offset 0; the
(source_file, source_event_id) UNIQUE index keeps re-walks idempotent
(rows already in the DB are no-ops, missing rows get inserted).

` + "`scan --force`" + ` is the recovery path when you notice gaps in the
Actions tab — typically a watcher that fell behind because of fsnotify
event drops or a daemon restart that lost in-flight state. The
dashboard's "Run all" button on the Backfill tab calls this path
first, then runs the surgical column-update backfills (--message-id,
--cache-tier, etc.) on top.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			w, cleanup, err := buildWatcher(cmd.Context(), configPath)
			if err != nil {
				return err
			}
			defer cleanup()
			var res watcher.ScanResult
			if force {
				res, err = w.Rescan(cmd.Context())
			} else {
				res, err = w.Scan(cmd.Context())
			}
			if err != nil {
				return err
			}
			label := "scan"
			if force {
				label = "rescan (from zero)"
			}
			fmt.Fprintf(cmd.OutOrStdout(),
				"%s complete: files_processed=%d errors=%d\n",
				label, res.FilesProcessed, res.Errors)
			return nil
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "", "Path to config.toml (defaults to ~/.observer/config.toml)")
	cmd.Flags().BoolVar(&force, "force", false, "Ignore saved parse cursors and re-walk every file from offset 0 (recovery path for watcher gaps)")
	return cmd
}

func newWatchCmd() *cobra.Command {
	var configPath string
	cmd := &cobra.Command{
		Use:   "watch",
		Short: "Start the fsnotify-based live watcher daemon",
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := signal.NotifyContext(cmd.Context(), os.Interrupt, syscall.SIGTERM)
			defer cancel()

			w, cleanup, err := buildWatcher(ctx, configPath)
			if err != nil {
				return err
			}
			defer cleanup()
			fmt.Fprintln(cmd.OutOrStdout(), "watcher running — ctrl-c to stop")
			if err := w.Watch(ctx); err != nil && !errors.Is(err, context.Canceled) {
				return err
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "", "Path to config.toml (defaults to ~/.observer/config.toml)")
	return cmd
}

// buildWatcher loads config, opens the DB, registers adapters, and returns a
// configured watcher plus a cleanup closure. Runs a retention pass first
// when prune_on_startup is set (spec §19).
// defaultAdapters returns the set of JSONL-watching adapters the
// observer registers in production. Cursor is intentionally absent —
// its capture path is hook-driven, not file-watching. Single source
// of truth so the watcher and the dashboard's health endpoint share
// the same "is this a recognised session file?" answer.
func defaultAdapters() []adapter.Adapter {
	return []adapter.Adapter{
		claudecode.New(),
		codex.New(),
		cline.New(),
		copilot.New(),
		openclaw.New(),
		opencode.New(),
		pi.New(),
	}
}

// recognizesSessionFile returns a predicate matching any of the
// default adapters' IsSessionFile checks. Used by the dashboard's
// /api/health/watcher endpoint to filter out orphaned parse_cursors
// rows (paths an older adapter version once tracked but no current
// adapter recognises) from the "behind" count — without this filter
// the user-visible banner shows orphan rows forever, since Rescan
// only re-walks paths that some adapter still claims.
func recognizesSessionFile() func(string) bool {
	adapters := defaultAdapters()
	return func(path string) bool {
		for _, a := range adapters {
			if a.IsSessionFile(path) {
				return true
			}
		}
		return false
	}
}

func buildWatcher(ctx context.Context, configPath string) (*watcher.Watcher, func(), error) {
	cfg, err := config.Load(config.LoadOptions{GlobalPath: configPath})
	if err != nil {
		return nil, nil, fmt.Errorf("load config: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(cfg.Observer.DBPath), 0o755); err != nil {
		return nil, nil, fmt.Errorf("ensure db dir: %w", err)
	}
	database, err := db.Open(ctx, db.Options{Path: cfg.Observer.DBPath})
	if err != nil {
		return nil, nil, fmt.Errorf("open db %s: %w", cfg.Observer.DBPath, err)
	}

	logger := newLogger(cfg.Observer.LogLevel)
	if cfg.Observer.Retention.PruneOnStartup {
		if res, err := runRetention(ctx, cfg, database); err != nil {
			logger.Warn("retention startup pass failed", "err", err)
		} else if res.ActionsDeleted+res.LogEntriesDeleted+res.OrphanedSessionsDeleted+res.FileStateDeleted > 0 {
			logger.Info("retention startup pass",
				"actions", res.ActionsDeleted, "sessions", res.OrphanedSessionsDeleted,
				"logs", res.LogEntriesDeleted, "file_state", res.FileStateDeleted,
				"duration_ms", res.DurationMs)
		}
	}

	reg := adapter.NewRegistry()
	for _, a := range defaultAdapters() {
		reg.Register(a)
	}
	// Surface what the cross-mount detector picked up so users know
	// observer-in-WSL2 actually saw their Windows-side tool data (or
	// vice-versa). Silent on pure-Linux / pure-macOS / pure-Windows
	// hosts where ExtraHomes returns nil.
	for _, h := range crossmount.ExtraHomes() {
		logger.Info("crossmount: detected extra home",
			"path", h.Path, "os", h.OS, "origin", h.Origin)
	}
	// Auto-enable Copilot Chat's debug-log capture across every
	// cross-mount-resolved $HOME's VS Code install. Without this flip,
	// Copilot writes only a session_start line to main.jsonl and the
	// adapter has nothing to ingest. Per user direction the flip is
	// automatic — but EnsureDebugEnabled logs INFO whenever it
	// actually changes a file so the user sees what observer touched.
	// Idempotent across restarts; silent steady state.
	copilot.EnsureDebugEnabled(ctx, logger, crossmount.AllHomes())
	var classifier *freshness.Classifier
	if cfg.Observer.Freshness.EnableContentHashing {
		classifier = freshness.New(database, freshness.Options{
			MaxHashSizeMB:    cfg.Observer.Freshness.MaxHashFileSizeMB,
			IgnorePatterns:   cfg.Observer.Freshness.IgnorePatterns,
			FastPathStatOnly: cfg.Observer.Freshness.FastPathStatOnly,
		})
	}
	var indexer *indexing.Indexer
	if cfg.Compression.Indexing.Enabled {
		indexer = indexing.New(database, cfg.Compression.Indexing.MaxExcerptBytes)
	}
	w := watcher.New(store.New(database), reg, watcher.Options{
		Logger: logger,
		NativePredicate: map[string]func(string) bool{
			"claude-code": claudecode.IsNativeTool,
		},
		Allow:        cfg.Observer.Watch.EnabledAdapters,
		PollInterval: time.Duration(cfg.Observer.Watch.PollIntervalSeconds) * time.Second,
		Classifier:   classifier,
		Indexer:      indexer,
	})

	cleanup := func() { _ = database.Close() }
	return w, cleanup, nil
}

func newLogger(level string) *slog.Logger {
	var lvl slog.Level
	switch level {
	case "debug":
		lvl = slog.LevelDebug
	case "warn":
		lvl = slog.LevelWarn
	case "error":
		lvl = slog.LevelError
	default:
		lvl = slog.LevelInfo
	}
	return slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: lvl}))
}
