package tooltax_test

// corpusRow is one measured (tool, raw_tool_name) pair from the live
// action corpus, with the action type tooltax must produce for it.
type corpusRow struct {
	tool   string
	native string
	want   string
}

// corpusNatives is THE per-row test table (plan WP-T1: "one test case per
// row"). It is the complete DISTINCT (tool, action_type, raw_tool_name)
// set for tool-call-shaped action types measured against the live
// 321,675-row corpus on 2026-07-31:
//
//	SELECT tool, action_type, raw_tool_name, COUNT(*) FROM actions
//	WHERE action_type IN ('read_file','write_file','edit_file',
//	  'run_command','search_text','search_files','web_search','web_fetch',
//	  'browser_action','mcp_call','spawn_subagent','todo_update',
//	  'ask_user','unknown')
//	  AND raw_tool_name IS NOT NULL AND raw_tool_name <> ''
//	GROUP BY tool, action_type, raw_tool_name;   -- 225 rows
//
// It is split in two halves on purpose:
//
//   - corpusKnownNatives (163 rows): the adapters ALREADY classify these.
//     want is the action type the corpus row carries, so this half proves
//     tooltax reproduces shipped behaviour exactly — a regression gate for
//     the WP-T3 adapter conversion.
//   - corpusUnknownNatives (62 rows): these currently land in `unknown`.
//     want is the taxonomy DECISION this work package makes, so this half
//     is the specification of the repair WP-T4's backfill migration will
//     apply.
var corpusKnownNatives = []corpusRow{
	{"antigravity", "structured.artifact_write", "edit_file"},
	{"antigravity", "structured.file_view", "read_file"},
	{"antigravity", "structured.run_command", "run_command"},
	{"claude-code", "AskUserQuestion", "ask_user"},
	{"claude-code", "Edit", "edit_file"},
	{"claude-code", "mcp__claude-in-chrome__computer", "mcp_call"},
	{"claude-code", "mcp__observer__get_file", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__javascript_tool", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__tabs_context_mcp", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__navigate", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__list_connected_browsers", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__read_network_requests", "mcp_call"},
	{"claude-code", "mcp__observer__search_past_outputs", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__find", "mcp_call"},
	{"claude-code", "mcp__observer__get_symbols", "mcp_call"},
	{"claude-code", "mcp__observer__get_last_test_result", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__browser_batch", "mcp_call"},
	{"claude-code", "mcp__ccd_session__mark_chapter", "mcp_call"},
	{"claude-code", "mcp__observer__cache_status", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__tabs_create_mcp", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__tabs_close_mcp", "mcp_call"},
	{"claude-code", "mcp__observer__search_symbols", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__read_page", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__read_console_messages", "mcp_call"},
	{"claude-code", "mcp__observer__check_file_freshness", "mcp_call"},
	{"claude-code", "mcp__observer__get_session_summary", "mcp_call"},
	{"claude-code", "mcp__observer__check_command_freshness", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__get_page_text", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__select_browser", "mcp_call"},
	{"claude-code", "mcp__observer__get_suggestions", "mcp_call"},
	{"claude-code", "mcp__observer__get_project_patterns", "mcp_call"},
	{"claude-code", "mcp__observer__get_file_history", "mcp_call"},
	{"claude-code", "mcp__observer__get_cost_summary", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__file_upload", "mcp_call"},
	{"claude-code", "mcp__Claude_Browser__resize_window", "mcp_call"},
	{"claude-code", "mcp__Claude_Browser__navigate", "mcp_call"},
	{"claude-code", "mcp__Claude_Browser__computer", "mcp_call"},
	{"claude-code", "mcp__observer__retrieve_stashed", "mcp_call"},
	{"claude-code", "mcp__observer__list_actions_around", "mcp_call"},
	{"claude-code", "mcp__observer__get_session_recovery_context", "mcp_call"},
	{"claude-code", "mcp__observer__get_failure_context", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__zoom", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__switch_browser", "mcp_call"},
	{"claude-code", "Read", "read_file"},
	{"claude-code", "Bash", "run_command"},
	{"claude-code", "PowerShell", "run_command"},
	{"claude-code", "Glob", "search_files"},
	{"claude-code", "Grep", "search_text"},
	{"claude-code", "Agent", "spawn_subagent"},
	{"claude-code", "TaskUpdate", "todo_update"},
	{"claude-code", "TaskCreate", "todo_update"},
	{"claude-code", "TaskStop", "todo_update"},
	{"claude-code", "TaskOutput", "todo_update"},
	{"claude-code", "TodoWrite", "todo_update"},
	{"claude-code", "TaskList", "todo_update"},
	{"claude-code", "TaskGet", "todo_update"},
	{"claude-code", "WebFetch", "web_fetch"},
	{"claude-code", "WebSearch", "web_search"},
	{"claude-code", "Write", "write_file"},
	{"cline-cli", "editor", "edit_file"},
	{"cline-cli", "read_files", "read_file"},
	{"cline-cli", "run_commands", "run_command"},
	{"codex", "patch_apply_end", "edit_file"},
	{"codex", "apply_patch", "edit_file"},
	{"codex", "mcp_tool_call_end", "mcp_call"},
	{"codex", "js", "mcp_call"},
	{"codex", "load_workspace_dependencies", "mcp_call"},
	{"codex", "search_past_outputs", "mcp_call"},
	{"codex", "list_actions_around", "mcp_call"},
	{"codex", "get_session_summary", "mcp_call"},
	{"codex", "get_action_details", "mcp_call"},
	{"codex", "get_session_recovery_context", "mcp_call"},
	{"codex", "get_project_patterns", "mcp_call"},
	{"codex", "get_last_test_result", "mcp_call"},
	{"codex", "view_image", "read_file"},
	{"codex", "exec", "run_command"},
	{"codex", "exec_command", "run_command"},
	{"codex", "shell_command", "run_command"},
	{"codex", "update_plan", "todo_update"},
	{"codex", "web_search_end", "web_search"},
	{"copilot", "read_file", "read_file"},
	{"copilot", "view_image", "read_file"},
	{"copilot", "list_dir", "search_files"},
	{"copilot", "grep_search", "search_text"},
	{"copilot", "create_file", "write_file"},
	{"copilot-cli", "edit", "edit_file"},
	{"copilot-cli", "view", "read_file"},
	{"copilot-cli", "powershell", "run_command"},
	{"copilot-cli", "bash", "run_command"},
	{"copilot-cli", "glob", "search_files"},
	{"copilot-cli", "web_fetch", "web_fetch"},
	{"copilot-cli", "create", "write_file"},
	{"cowork", "AskUserQuestion", "ask_user"},
	{"cowork", "Edit", "edit_file"},
	{"cowork", "ToolSearch", "mcp_call"},
	{"cowork", "mcp__cowork__present_files", "mcp_call"},
	{"cowork", "Skill", "mcp_call"},
	{"cowork", "mcp__claude-in-chrome__navigate", "mcp_call"},
	{"cowork", "mcp__claude-in-chrome__get_page_text", "mcp_call"},
	{"cowork", "mcp__visualize__show_widget", "mcp_call"},
	{"cowork", "mcp__claude-in-chrome__tabs_context_mcp", "mcp_call"},
	{"cowork", "mcp__visualize__read_me", "mcp_call"},
	{"cowork", "mcp__cowork__send_user_message", "mcp_call"},
	{"cowork", "mcp__cowork__request_cowork_directory", "mcp_call"},
	{"cowork", "Read", "read_file"},
	{"cowork", "mcp__workspace__bash", "run_command"},
	{"cowork", "Bash", "run_command"},
	{"cowork", "Glob", "search_files"},
	{"cowork", "Grep", "search_text"},
	{"cowork", "Agent", "spawn_subagent"},
	{"cowork", "TaskUpdate", "todo_update"},
	{"cowork", "TaskCreate", "todo_update"},
	{"cowork", "mcp__workspace__web_fetch", "web_fetch"},
	{"cowork", "WebSearch", "web_search"},
	{"cowork", "Write", "write_file"},
	{"crush", "bash", "run_command"},
	{"crush", "ls", "search_files"},
	{"crush", "write", "write_file"},
	{"cursor", "afterFileEdit", "edit_file"},
	{"cursor", "Read", "read_file"},
	{"cursor", "beforeReadFile", "read_file"},
	{"cursor", "Shell", "run_command"},
	{"cursor", "beforeShellExecution", "run_command"},
	{"cursor", "Glob", "search_files"},
	{"cursor", "Grep", "search_text"},
	{"cursor", "SemanticSearch", "search_text"},
	{"devin", "read", "read_file"},
	{"devin", "exec", "run_command"},
	{"devin", "write", "write_file"},
	{"goose", "shell", "run_command"},
	{"goose", "write", "write_file"},
	{"grok", "search_replace", "edit_file"},
	{"grok", "read_file", "read_file"},
	{"grok", "run_terminal_command", "run_command"},
	{"grok", "list_dir", "search_files"},
	{"grok", "write", "write_file"},
	{"hermes", "read_file", "read_file"},
	{"hermes", "terminal", "run_command"},
	{"hermes", "write_file", "write_file"},
	{"kilo-code-cli", "read", "read_file"},
	{"kilo-code-cli", "bash", "run_command"},
	{"kilo-code-cli", "glob", "search_files"},
	{"kilo-code-cli", "task", "spawn_subagent"},
	{"kilo-code-cli", "write", "write_file"},
	{"kimi-code", "Bash", "run_command"},
	{"kimi-code", "Write", "write_file"},
	{"kiro-cli", "execute_bash", "run_command"},
	{"kiro-cli", "fs_write", "write_file"},
	{"openclaw", "read", "read_file"},
	{"openclaw", "exec", "run_command"},
	{"opencode", "read", "read_file"},
	{"opencode", "bash", "run_command"},
	{"opencode", "glob", "search_files"},
	{"opencode", "grep", "search_text"},
	{"pi", "edit", "edit_file"},
	{"pi", "read", "read_file"},
	{"pi", "bash", "run_command"},
	{"qoder", "Read", "read_file"},
	{"qoder", "Bash", "run_command"},
	{"qoder", "Agent", "spawn_subagent"},
	{"qoder", "Write", "write_file"},
	{"qwen-code", "run_shell_command", "run_command"},
	{"qwen-code", "write_file", "write_file"},
}

var corpusUnknownNatives = []corpusRow{
	{"claude-code", "ToolSearch", "tool_search"},
	{"claude-code", "Monitor", "agent_control"},
	{"claude-code", "SendMessage", "agent_message"},
	{"claude-code", "StructuredOutput", "harness_call"},
	{"claude-code", "mcp__claude-in-chrome__computer", "mcp_call"},
	{"claude-code", "ScheduleWakeup", "schedule"},
	{"claude-code", "Skill", "skill_invoke"},
	{"claude-code", "SendUserFile", "harness_call"},
	{"claude-code", "mcp__claude-in-chrome__javascript_tool", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__tabs_context_mcp", "mcp_call"},
	{"claude-code", "mcp__observer__retrieve_stashed", "mcp_call"},
	{"claude-code", "PushNotification", "notification"},
	{"claude-code", "mcp__claude-in-chrome__navigate", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__browser_batch", "mcp_call"},
	{"claude-code", "CronCreate", "schedule"},
	{"claude-code", "mcp__ccd_session__mark_chapter", "mcp_call"},
	{"claude-code", "CronDelete", "schedule"},
	{"claude-code", "mcp__claude-in-chrome__read_page", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__get_page_text", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__find", "mcp_call"},
	{"claude-code", "mcp__observer__get_file", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__file_upload", "mcp_call"},
	{"claude-code", "bash", "run_command"},
	{"claude-code", "EnterWorktree", "worktree_create"},
	{"claude-code", "Artifact", "harness_call"},
	{"claude-code", "mcp__claude-in-chrome__read_network_requests", "mcp_call"},
	{"claude-code", "Workflow", "harness_call"},
	{"claude-code", "CronList", "schedule"},
	{"claude-code", "mcp__observer__search_symbols", "mcp_call"},
	{"claude-code", "mcp__observer__get_relations", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__tabs_create_mcp", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__resize_window", "mcp_call"},
	{"claude-code", "mcp__claude-in-chrome__list_connected_browsers", "mcp_call"},
	{"claude-code", "mcp__ccd_session__spawn_task", "mcp_call"},
	{"claude-code", "ExitWorktree", "worktree_remove"},
	{"codex", "wait", "subagent_wait"},
	{"codex", "wait_agent", "subagent_wait"},
	{"codex", "send_message", "agent_message"},
	{"codex", "write_stdin", "stdin_write"},
	{"codex", "list_agents", "agent_control"},
	{"codex", "followup_task", "agent_message"},
	{"codex", "spawn_agent", "spawn_subagent"},
	{"codex", "Bash", "run_command"},
	{"codex", "interrupt_agent", "agent_control"},
	{"codex", "request_user_input", "ask_user"},
	{"codex", "imagegen", "harness_call"},
	{"codex", "read_thread_terminal", "agent_control"},
	{"codex", "read_thread", "agent_control"},
	{"codex", "mcp__observer__get_session_summary", "mcp_call"},
	{"codex", "mcp__observer__get_project_patterns", "mcp_call"},
	{"codex", "mcp__observer__get_action_details", "mcp_call"},
	{"codex", "list_threads", "agent_control"},
	{"codex", "get_file", "mcp_call"},
	{"copilot-cli", "report_intent", "unknown"},
	{"copilot-cli", "fetch_copilot_cli_documentation", "harness_call"},
	{"copilot-cli", "ask_user", "ask_user"},
	{"cursor", "Write", "write_file"},
	{"cursor", "Delete", "edit_file"},
	{"kilo-code-cli", "kilo-code-cli.step_finish", "harness_call"},
	{"kiro-cli", "execute_cmd", "run_command"},
	{"opencode", "opencode.step_finish", "harness_call"},
	{"qwen-code", "qwen-code.slash_command", "user_prompt_expansion"},
}
