package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/marmutapp/superbased-observer/internal/integration"
)

// committedPath is where the generated manifest lives, relative to this
// package dir.
const committedPath = "../../website/tools/tool-count-manifest.json"

func generateOrFail(t *testing.T) []byte {
	t.Helper()
	data, err := generate()
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return data
}

func decodeOrFail(t *testing.T, data []byte) doc {
	t.Helper()
	var d doc
	if err := json.Unmarshal(data, &d); err != nil {
		t.Fatalf("unmarshal generated JSON: %v", err)
	}
	return d
}

// TestGenerateIsDeterministic is the precondition for the drift gate: if
// generate() were order-unstable (a ranged map, a clock, an environment
// read) `make verify-tool-count-build` would fail at random.
func TestGenerateIsDeterministic(t *testing.T) {
	first := generateOrFail(t)
	for run := 2; run <= 4; run++ {
		next := generateOrFail(t)
		if !bytes.Equal(next, first) {
			t.Fatalf("run %d differs from run 1:\n--- run 1 ---\n%s\n--- run %d ---\n%s",
				run, first, run, next)
		}
	}
}

// TestGeneratedMatchesCommitted is the in-test half of the CI gate: it
// fails the Go suite (not just the shell gate) when somebody adds/removes
// an internal/integration registry row, or edits foldGroups, without
// running `make tool-count-build`.
func TestGeneratedMatchesCommitted(t *testing.T) {
	got := generateOrFail(t)
	want, err := os.ReadFile(committedPath)
	if err != nil {
		t.Fatalf("read committed %s: %v", committedPath, err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s is stale — run `make tool-count-build` and commit.\n"+
			"committed %d bytes, regenerated %d bytes", committedPath, len(want), len(got))
	}
}

// TestTrailingNewlineDiscipline pins the byte-level shape the gate diffs:
// valid JSON, 2-space indent, exactly one trailing newline.
func TestTrailingNewlineDiscipline(t *testing.T) {
	data := generateOrFail(t)
	if !json.Valid(data) {
		t.Fatal("generated bytes are not valid JSON")
	}
	if !bytes.HasSuffix(data, []byte("\n")) {
		t.Error("generated file does not end with a newline")
	}
	if bytes.HasSuffix(data, []byte("\n\n")) {
		t.Error("generated file ends with more than one newline")
	}
	if !bytes.Contains(data, []byte("\n  \"registryRowCount\": ")) {
		t.Error("generated file is not 2-space indented")
	}
}

// TestFamiliesPartitionEveryRegistryRow proves buildFamilies is a true
// partition of the live registry: every row appears in exactly one
// family, and every family member is a live row. This is what makes the
// generator fail loudly (rather than silently under/over count) the
// moment foldGroups falls out of sync with internal/integration.
func TestFamiliesPartitionEveryRegistryRow(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))

	rows := integration.Tools()
	if d.RegistryRowCount != len(rows) {
		t.Errorf("registryRowCount = %d, internal/integration.Tools() has %d", d.RegistryRowCount, len(rows))
	}

	seen := make(map[string]string, len(rows)) // row -> family key
	memberTotal := 0
	for _, f := range d.Families {
		if f.Weight <= 0 {
			t.Errorf("family %q has non-positive weight %d", f.Key, f.Weight)
		}
		if len(f.Members) == 0 {
			t.Errorf("family %q has no members", f.Key)
		}
		for _, m := range f.Members {
			memberTotal++
			if prior, dup := seen[m]; dup {
				t.Errorf("registry row %q is claimed by both family %q and %q", m, prior, f.Key)
			}
			seen[m] = f.Key
		}
	}
	if memberTotal != len(rows) {
		t.Errorf("families claim %d total members, registry has %d rows", memberTotal, len(rows))
	}
	for _, r := range rows {
		if _, ok := seen[r]; !ok {
			t.Errorf("registry row %q is not covered by any family", r)
		}
	}
}

// TestAdapterCountIsSumOfWeights pins the arithmetic the whole manifest
// exists to make explicit: AdapterCount is exactly the sum of every
// family's Weight, nothing else.
func TestAdapterCountIsSumOfWeights(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))
	sum := 0
	for _, f := range d.Families {
		sum += f.Weight
	}
	if d.AdapterCount != sum {
		t.Errorf("adapterCount = %d, but families sum to %d", d.AdapterCount, sum)
	}
}

// TestKnownFoldGroupsPresent pins the three documented editorial folds by
// name and weight, written out by hand (not derived from foldGroups) so a
// silent edit to the fold data itself is loud.
func TestKnownFoldGroupsPresent(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))

	want := map[string]struct {
		weight  int
		members []string
	}{
		"antigravity": {1, []string{"antigravity", "antigravity-cli"}},
		"kilo-code":   {2, []string{"kilo-code", "kilo-code-cli"}},
		"browserchat": {1, []string{
			"chatgpt-web", "claude-web", "perplexity-web", "gemini-web", "copilot-web",
		}},
	}

	byKey := make(map[string]family, len(d.Families))
	for _, f := range d.Families {
		byKey[f.Key] = f
	}

	for key, w := range want {
		got, ok := byKey[key]
		if !ok {
			t.Errorf("expected fold-group family %q missing from the manifest", key)
			continue
		}
		if got.Weight != w.weight {
			t.Errorf("family %q weight = %d, want %d", key, got.Weight, w.weight)
		}
		if len(got.Members) != len(w.members) {
			t.Errorf("family %q has %d members, want %d", key, len(got.Members), len(w.members))
			continue
		}
		gotSet := make(map[string]struct{}, len(got.Members))
		for _, m := range got.Members {
			gotSet[m] = struct{}{}
		}
		for _, m := range w.members {
			if _, ok := gotSet[m]; !ok {
				t.Errorf("family %q is missing expected member %q", key, m)
			}
		}
		if got.Note == "" {
			t.Errorf("fold-group family %q has no Note explaining the fold", key)
		}
	}
}

// TestUnfoldedRowsAreWeightOne pins the default: any registry row not
// named in a fold group is its own family with weight 1 — never silently
// folded or double-counted.
func TestUnfoldedRowsAreWeightOne(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))

	folded := map[string]struct{}{}
	for _, g := range foldGroups {
		for _, m := range g.Members {
			folded[m] = struct{}{}
		}
	}

	byKey := make(map[string]family, len(d.Families))
	for _, f := range d.Families {
		byKey[f.Key] = f
	}

	for _, row := range integration.Tools() {
		if _, isFolded := folded[row]; isFolded {
			continue
		}
		f, ok := byKey[row]
		if !ok {
			t.Errorf("unfolded row %q has no matching weight-1 family", row)
			continue
		}
		if f.Weight != 1 || len(f.Members) != 1 || f.Members[0] != row {
			t.Errorf("unfolded row %q family = %+v, want weight 1 and members [%s]", row, f, row)
		}
	}
}

// TestWriteCreatesParentDir covers the gate's `-outdir /tmp/...` path.
func TestWriteCreatesParentDir(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "nested", manifestName)
	data := generateOrFail(t)
	if err := write(out, data); err != nil {
		t.Fatalf("write: %v", err)
	}
	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if !bytes.Equal(got, data) {
		t.Error("written bytes differ from generated bytes")
	}
}

// TestFoldGroupMembersExistInRegistry pins buildFamilies' own loud
// failure path: if a foldGroups member is renamed/removed, generate()
// must error rather than silently shrinking the count.
func TestFoldGroupMembersExistInRegistry(t *testing.T) {
	live := make(map[string]struct{})
	for _, r := range integration.Tools() {
		live[r] = struct{}{}
	}
	for _, g := range foldGroups {
		for _, m := range g.Members {
			if _, ok := live[m]; !ok {
				t.Errorf("foldGroups %q references %q, which is not a live internal/integration row — "+
					"update foldGroups", g.Key, m)
			}
		}
	}
}
