-- 078_assistant_text_action_type_relabel.sql — GENERATED by internal/db/asstbackfillgen.
-- DO NOT EDIT BY HAND.
--
--   regenerate: make assistant-migration-build
--   drift gate: make verify-assistant-migration
--
-- WHAT THIS REPAIRS. The `<tool>.assistant_text` family is the model's
-- natural-language response text, recorded PER MESSAGE — one row per text
-- block / text part / prose chunk. Adapters historically typed those rows
-- `task_complete`, which is the wrong semantic label: the assistant talking
-- mid-turn is not a task completion (85-87 % of claude-code and codex turns
-- carry MORE THAN ONE such row). models.ActionAssistantMessage was added for
-- exactly this, five adapters were swept to it in an earlier cycle, and
-- WP-T6/B2a swept the remaining seven emit sites. This migration applies the
-- same relabel to the rows already on disk, so a per-type query stops being
-- silently wrong about which half of history it is reading.
--
-- WHAT STAYS `task_complete`. Evidence-grounded turn TERMINI: rows an adapter
-- emitted because the source stream said the turn ended. Those keep their
-- type and their own raw names — openclaw `message.assistant.stop`
-- (stop-reason gated), kilo-code-cli `assistant.stop`, opencode
-- `complete:` rows, codex's `task_complete` event_msg, cline
-- `attempt_completion`, cline-cli `submit_and_exit`, antigravity
-- `structured.final_summary` — none of which this migration can reach,
-- because it is scoped to exact `.assistant_text` raw names.
--
-- THE ONE NON-OBVIOUS CARVE-OUT. claude-code has TWO producers of
-- `claudecode.assistant_text` with genuinely different semantics: the
-- JSONL walker (one row per text block, mid-turn) and the Stop HOOK
-- (fires once on turn end, carries last_assistant_message). The hook rows
-- ARE turn-terminal and must keep `task_complete`. They are exactly separable
-- by `source_file = 'claude-code:hook'` — every observer hook event
-- carries that sentinel and no transcript row ever does — so the
-- claude-code statement below carries an explicit carve-out. A blanket
-- rewrite over the raw name would mislabel those rows.
--
-- THE GUARD — four ANDed predicates, all four load-bearing:
--
--   1. EXACT OLD->NEW PAIR. `SET action_type = 'assistant_message'` always appears
--      together with `AND action_type = 'task_complete'`, never a bare SET.
--      This is 078's replacement for 077's `= 'unknown'` guard: it makes
--      each statement a pair rewrite, so a row an adapter deliberately
--      typed something else is untouchable.
--   2. EXACT RAW-NAME LITERALS, never `LIKE '%.assistant_text'`. 077's
--      rationale applies verbatim (SQLite LIKE is ASCII case-INSENSITIVE
--      and `_` is a wildcard — and these names are full of underscores),
--      plus a forward-compat hazard 077 did not face: a LIKE pattern would
--      silently capture any FUTURE `.assistant_text` name added after this
--      migration shipped, which by then may mean something else.
--   3. TOOL-SCOPED, one statement per actions.tool, exactly as 077 does.
--      Note a raw name can appear under more than one tool because three
--      adapters RETAG after parsing (codex -> open-interpreter, cline ->
--      kilo-code, antigravity -> antigravity-cli, the last of which
--      migration 071 also applied to history); every reachable tool is
--      enumerated, so no island of rows is left behind.
--   4. THE SOURCE-FILE CARVE-OUT described above. It is written
--      `COALESCE(source_file, '') <> '...'` because actions.source_file is
--      NULLable (001_initial.sql) and a bare `<>` is NULL — hence FALSE —
--      for a NULL source_file, which would silently SKIP walker rows that
--      have no source file rather than rewriting them.
--
-- IDEMPOTENT BY CONSTRUCTION. Predicate 1 means run 2 matches nothing: the
-- rows run 1 touched no longer have action_type = 'task_complete'.
--
-- NODE-LOCAL. actions.action_type is already on the org push wire; this
-- changes values, not shape, so there is no paired server migration.

-- aider.assistant_text — internal/adapter/aider/parse.go::flushAssistant (seven prose boundaries)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'aider'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'aider.assistant_text';

-- structured.assistant_text — internal/adapter/antigravity/structured.go (one row per synthesized step)
-- transcript.assistant_text — internal/adapter/antigravity/transcript_cli.go (one row per MODEL/PLANNER_RESPONSE step)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'antigravity'
   AND action_type = 'task_complete'
   AND raw_tool_name IN (
     'structured.assistant_text',
     'transcript.assistant_text'
   );

-- structured.assistant_text — internal/adapter/antigravity/structured.go (one row per synthesized step)
-- transcript.assistant_text — internal/adapter/antigravity/transcript_cli.go (one row per MODEL/PLANNER_RESPONSE step)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'task_complete'
   AND raw_tool_name IN (
     'structured.assistant_text',
     'transcript.assistant_text'
   );

-- claudecode.assistant_text — internal/adapter/claudecode/adapter.go::assistantTextEvent (one row per text content block)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'claude-code'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'claudecode.assistant_text'
   AND COALESCE(source_file, '') <> 'claude-code:hook';

-- cline.assistant_text — internal/adapter/cline/adapter.go (raw name built as toolID+".assistant_text"; already emits assistant_message)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'cline'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'cline.assistant_text';

-- codex.assistant_text — internal/adapter/codex/adapter.go::buildAgentMessageEvent (one row per agent_message)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'codex'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'codex.assistant_text';

-- cowork.assistant_text — internal/adapter/cowork/adapter.go (already emits assistant_message)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'cowork'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'cowork.assistant_text';

-- crush.assistant_text — internal/adapter/crush/adapter.go::assistantTextEvent (one row per text part)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'crush'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'crush.assistant_text';

-- cursor.assistant_text — internal/adapter/cursor/adapter.go (already emits assistant_message)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'cursor'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'cursor.assistant_text';

-- cline.assistant_text — internal/adapter/cline/adapter.go (raw name built as toolID+".assistant_text"; already emits assistant_message)
-- roo-code.assistant_text — internal/adapter/cline/adapter.go, roo-code tool id (same emit site as cline.assistant_text)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'kilo-code'
   AND action_type = 'task_complete'
   AND raw_tool_name IN (
     'cline.assistant_text',
     'roo-code.assistant_text'
   );

-- kilo-code-cli.assistant_text — internal/adapter/kilocode/adapter.go (one row per text part)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'kilo-code-cli.assistant_text';

-- codex.assistant_text — internal/adapter/codex/adapter.go::buildAgentMessageEvent (one row per agent_message)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'open-interpreter'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'codex.assistant_text';

-- openclaw.assistant_text — internal/adapter/openclaw/adapter.go — THE EXEMPLAR: per-part assistant_message plus a separate stop-gated message.assistant.stop task_complete row
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'openclaw'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'openclaw.assistant_text';

-- opencode.assistant_text — internal/adapter/opencode/adapter.go (already emits assistant_message)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'opencode'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'opencode.assistant_text';

-- roo-code.assistant_text — internal/adapter/cline/adapter.go, roo-code tool id (same emit site as cline.assistant_text)
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'roo-code'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'roo-code.assistant_text';
