-- 079_reasoning_row_convergence.sql — GENERATED by internal/db/reasoninggen.
-- DO NOT EDIT BY HAND.
--
--   regenerate: make reasoning-migration-build
--   drift gate: make verify-reasoning-migration
--
-- APPLY-ONCE, AND WHY REGENERATING IS STILL CORRECT TODAY. Migrations are
-- keyed by version, not by content, so once a release has carried 079 its
-- bytes are frozen and a shape change needs a NEW migration. That line has
-- NOT been crossed: 079 is committed but UNRELEASED and applied nowhere
-- (the review's own node was verified at schema 78). Every regeneration
-- before the release that ships it is a normal edit of an unapplied file.
--
-- WHAT THIS REPAIRS (B3, docs/plans/b3-reasoning-convergence-plan-2026-07-31.md).
-- Model reasoning is NOT an action. It is something the model did on the way
-- to an action, and the taxonomy carries it as `preceding_reasoning` on the
-- successor event — grok's shape, which the B3 arc converged every adapter
-- onto. Fifteen emit sites used to mint a SEPARATE row for it instead, typed
-- `task_complete`, which produced 15,734 phantom "task completions" in the
-- live corpus. The emission half of B3 stopped all fifteen. This migration is
-- the historical half.
--
-- WHAT IT DELETES — and ONLY this. The codex/open-interpreter PLACEHOLDER
-- rows: the `(reasoning)` and `(encrypted reasoning, N bytes)` rows the retired
-- emit site wrote when a reasoning item carried NO readable summary (15,040
-- of codex's 15,369). Those rows have no content, never had content, and
-- were never threaded anywhere: the encrypted body is opaque and the
-- placeholder string is a rendering of its LENGTH. Deleting them removes
-- rows, not information.
--
-- WHAT IT KEEPS. Everything content-bearing, including rows this migration
-- could technically reach:
--
--   * codex/open-interpreter reasoning rows whose target is REAL SUMMARY TEXT
--     (329 rows) — the predicate's target shapes exclude them by construction.
--   * gemini `gemini.reasoning` rows (15). Deleting them would be LOSSY and was
--     re-verified as such: their `raw_tool_output` holds 211–2,926 bytes while the
--     successor's `preceding_reasoning` holds a 200-char preview, and only 10 of
--     the 15 successors carry even that. The bytes exist in exactly one place.
--   * every other tool's reasoning rows (365 across 11 minority emitters).
--
-- ACCEPTED RESIDUE: ~679 content-bearing reasoning rows across 12 tools
-- survive this migration by design. They are historical rows of a shape no
-- adapter mints any more. A future arc may re-thread them onto their
-- successors; deleting them here would be data loss, and re-typing them
-- would be inventing a classification the producer never recorded.
--
-- THE DELETE PREDICATE — five ANDed conditions, all five load-bearing:
--
--   1. TOOL-SCOPED, one statement per actions.tool ('codex' and
--      'open-interpreter', the NewOpenInterpreter retag of the same parser).
--      Never an unscoped delete.
--   2. EXACT RAW-NAME LITERAL `codex.reasoning`, never `LIKE '%.reasoning'`.
--      077/078's rationale applies verbatim (SQLite LIKE is ASCII
--      case-INSENSITIVE and `_` is a wildcard) and the stakes are higher here:
--      a LIKE pattern would reach every OTHER tool's reasoning rows, which
--      this migration must not touch. NO LIKE and NO GLOB appears anywhere
--      in this file.
--   3. EXACT ACTION TYPE `task_complete`. A row somebody re-typed on
--      purpose is out of reach.
--   4. THE PRODUCER INVARIANT `raw_tool_output = target`. The retired emit site
--      wrote the same placeholder string into both columns; a row where they
--      differ carries something the placeholder producer never wrote.
--   5. THE EXACT TARGET SHAPES. Either the literal `(reasoning)`, or the
--      printf tail `(encrypted reasoning, %d bytes)` matched as a CANONICAL
--      POSITIVE `%d`, not as "some digits": prefix by substr, suffix by
--      substr from the end, the numeric segment bounded BETWEEN 1 AND 19
--      characters, its FIRST character bounded BETWEEN '1' AND '9', and the
--      whole segment required to trim to empty against the digit set. The
--      trim is how "all digits" is expressed without LIKE or GLOB (SQLite's
--      TRIM(X,Y) strips any Y-character from both ends, so a non-digit
--      anywhere survives and fails the test).
--
--      The two numeric bounds are not decoration. The producer's argument
--      was `len(encrypted body)` of a NON-EMPTY body, so `%d` could never
--      render a leading zero, never a bare `0`, and never more than 19
--      digits (the decimal width of the int64 ceiling). Without these
--      bounds the predicate would reach `(encrypted reasoning, 0 bytes)`,
--      `(encrypted reasoning, 0972 bytes)` and 20-digit counts — strings
--      this producer could not have written, i.e. somebody else's data.
--
-- THE HONEST CLAIM. This is PRODUCER-INVARIANT MATCHING, not a mathematical
-- proof of content-freeness. What is asserted: the predicate matches every
-- placeholder the retired producer could emit, and no row carrying real
-- summary text AND all five conditions was observed in the corpus. What is
-- NOT asserted: that no such row can exist. A reasoning summary whose text
-- happened to be exactly `(reasoning)` — or exactly the printf rendering of its
-- own encrypted length — would be indistinguishable from a placeholder, and
-- would be deleted. That is the residual, stated rather than hidden.
--
-- A KNOWN, DELIBERATE UNDER-REACH: condition 4 does not match rows whose
-- `raw_tool_output` is NULL (the column arrived in migration 027; any
-- placeholder row older than that has none). Those rows survive. Relaxing
-- the invariant to reach them would trade a guard for a handful of rows —
-- the wrong trade for a DELETE.
--
-- BEFORE THE DELETE: THE DEPENDENCY PROTOCOL. Seven tables reference
-- actions(id) with no ON DELETE CASCADE. Two are cleared, five have their
-- reference NULLed, in the order verified by
-- internal/retention/retention.go::deleteActionsOlder — the path that
-- already survived the live "FOREIGN KEY constraint failed (787)" regression
-- (2026-06-18) that left the actions table un-pruned. Skipping
-- `action_excerpts` would be worse than a constraint error: FTS5 search never
-- joins actions, so the excerpts would become SEARCHABLE GHOSTS of rows that
-- no longer exist. Every dependent statement is scoped by the SAME candidate
-- predicate as the delete.
--
-- FOLD-IN: the cursor `cursor.assistant_response` pair rewrite that 078's
-- `.assistant_text` scoping could not reach. devin's `devin.assistant_message`
-- task_complete rows are EXCLUDED — they come from a live branch keyed on the
-- provider's own finish_reason (adapter.go:265-267), which is exactly the
-- evidence `task_complete` is for.
--
-- THE ID HIGH-WATER MARKER. Before anything is deleted, `MAX(actions.id)` is
-- recorded in schema_meta under `migration_079_max_action_id`. actions.id is an
-- autoincrement rowid, i.e. insertion order, so "no phantom reasoning row was
-- minted after 079 applied" becomes a well-defined check: any offending row
-- has `id > marker`. It is recorded BEFORE the delete on purpose — recording
-- it after would leave surviving pre-079 rows above the mark and make the
-- check produce false positives.
--
-- DECAY, HONESTLY. The migration runner is atomic, but it coordinates DB
-- WRITERS, not binary versions: an old daemon that is still running after 079
-- applies will keep minting the rows this migration just deleted. Nothing
-- here can prevent that, and no write-boundary enforcement is being added in
-- this arc — that is the accepted trade. What exists instead: the marker makes
-- the decay MEASURABLE, the release notes and the daemon-restart runbook carry
-- the restart requirement, and a generator-side AST guard makes re-introducing
-- an emit site un-shippable going forward.
--
-- ORG DIVERGENCE, ACCEPTED. Org push is append-only
-- (internal/store/orgpush.go) and the server has no retraction rail, so rows
-- already pushed stay in org rollups after this local delete. The org side
-- holds counts and metadata only — never the placeholder content, which was
-- content-free to begin with. No retraction mechanism exists or is being
-- added for this.
--
-- IDEMPOTENT BY CONSTRUCTION. The deletes match nothing on a second run (the
-- rows are gone); the rewrite is an exact old->new pair, so run 2 finds no
-- row at the old type; the marker INSERT is `ON CONFLICT DO NOTHING`, so the
-- first-apply high-water mark is never overwritten.
--
-- NODE-LOCAL. No new table and no new column: schema_meta is the repo's
-- existing KV table and has never been on the org-push wire. actions.* shape
-- is unchanged, so there is no paired server migration.

-- ---------------------------------------------------------------
-- (0) ID high-water marker — recorded BEFORE anything is deleted.
--
-- actions.id is an autoincrement rowid, so it is insertion order. Any
-- reasoning row with id > this mark was minted AFTER 079 applied, which
-- is exactly the decay a still-running old daemon produces. ON CONFLICT
-- DO NOTHING keeps the FIRST apply's value authoritative.
-- ---------------------------------------------------------------
INSERT INTO schema_meta (key, value)
VALUES ('migration_079_max_action_id', (SELECT CAST(COALESCE(MAX(id), 0) AS TEXT) FROM actions))
ON CONFLICT(key) DO NOTHING;

-- ---------------------------------------------------------------
-- codex — dependency protocol, then the placeholder delete.
-- ---------------------------------------------------------------

-- FTS5 excerpts (001_initial.sql:160). The search path NEVER joins actions
-- (internal/compression/indexing/indexer.go), so a bare actions DELETE leaves
-- SEARCHABLE GHOSTS: rows the MCP search_past_outputs tool can still return
-- and whose action row no longer exists. ~15k of the delete candidates carry one.
DELETE FROM action_excerpts
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'codex'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- failure_context.action_id is NOT NULL REFERENCES actions(id) (001_initial.sql:141),
-- so the row cannot survive its action — it is deleted, not NULLed.
DELETE FROM failure_context
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'codex'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- file_state keeps its freshness value without the action link, so the
-- reference is NULLed rather than the row deleted (retention.go does the same).
UPDATE file_state
   SET last_action_id = NULL
 WHERE last_action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'codex'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- retrieval_signals preserves the K43 long tail on purpose (014_retrieval_signals.sql
-- comment: "orphan rows after action deletion are harmless"); NULL the link.
UPDATE retrieval_signals
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'codex'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- guard_events is an append-only, hash-CHAINED audit log with its own retention.
-- Deleting a row would break the chain; the action anchor is NULLed instead.
UPDATE guard_events
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'codex'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- process_runs carries its own retention horizon and stays useful unattributed.
UPDATE process_runs
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'codex'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- process_events, same as process_runs.
UPDATE process_events
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'codex'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- The delete itself. Same predicate, spelled inline.
DELETE FROM actions
 WHERE tool = 'codex'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'codex.reasoning'
   AND raw_tool_output = target
   AND (
         target = '(reasoning)'
      OR (
               substr(target, 1, 22) = '(encrypted reasoning, '
           AND substr(target, -7) = ' bytes)'
           AND length(target) - 29 BETWEEN 1 AND 19
           AND substr(target, 23, 1) BETWEEN '1' AND '9'
           AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
         )
       );

-- ---------------------------------------------------------------
-- open-interpreter — dependency protocol, then the placeholder delete.
-- ---------------------------------------------------------------

-- FTS5 excerpts (001_initial.sql:160). The search path NEVER joins actions
-- (internal/compression/indexing/indexer.go), so a bare actions DELETE leaves
-- SEARCHABLE GHOSTS: rows the MCP search_past_outputs tool can still return
-- and whose action row no longer exists. ~15k of the delete candidates carry one.
DELETE FROM action_excerpts
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'open-interpreter'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- failure_context.action_id is NOT NULL REFERENCES actions(id) (001_initial.sql:141),
-- so the row cannot survive its action — it is deleted, not NULLed.
DELETE FROM failure_context
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'open-interpreter'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- file_state keeps its freshness value without the action link, so the
-- reference is NULLed rather than the row deleted (retention.go does the same).
UPDATE file_state
   SET last_action_id = NULL
 WHERE last_action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'open-interpreter'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- retrieval_signals preserves the K43 long tail on purpose (014_retrieval_signals.sql
-- comment: "orphan rows after action deletion are harmless"); NULL the link.
UPDATE retrieval_signals
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'open-interpreter'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- guard_events is an append-only, hash-CHAINED audit log with its own retention.
-- Deleting a row would break the chain; the action anchor is NULLed instead.
UPDATE guard_events
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'open-interpreter'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- process_runs carries its own retention horizon and stays useful unattributed.
UPDATE process_runs
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'open-interpreter'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- process_events, same as process_runs.
UPDATE process_events
   SET action_id = NULL
 WHERE action_id IN (
   SELECT id
     FROM actions
    WHERE tool = 'open-interpreter'
      AND action_type = 'task_complete'
      AND raw_tool_name = 'codex.reasoning'
      AND raw_tool_output = target
      AND (
            target = '(reasoning)'
         OR (
                  substr(target, 1, 22) = '(encrypted reasoning, '
              AND substr(target, -7) = ' bytes)'
              AND length(target) - 29 BETWEEN 1 AND 19
              AND substr(target, 23, 1) BETWEEN '1' AND '9'
              AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
            )
          )
 );

-- The delete itself. Same predicate, spelled inline.
DELETE FROM actions
 WHERE tool = 'open-interpreter'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'codex.reasoning'
   AND raw_tool_output = target
   AND (
         target = '(reasoning)'
      OR (
               substr(target, 1, 22) = '(encrypted reasoning, '
           AND substr(target, -7) = ' bytes)'
           AND length(target) - 29 BETWEEN 1 AND 19
           AND substr(target, 23, 1) BETWEEN '1' AND '9'
           AND trim(substr(target, 23, length(target) - 29), '0123456789') = ''
         )
       );

-- ---------------------------------------------------------------
-- Fold-in: cursor / cursor.assistant_response — exact pair rewrite, 078's vocabulary.
-- internal/adapter/cursor/adapter.go:433 (EventAfterAgentResponse) types this
-- assistant_message unconditionally; the task_complete rows are pre-sweep history
-- (disjoint id ranges, b2-investigation.md §2.2).
-- ---------------------------------------------------------------
UPDATE actions
   SET action_type = 'assistant_message'
 WHERE tool = 'cursor'
   AND action_type = 'task_complete'
   AND raw_tool_name = 'cursor.assistant_response';
