// GENERATED by plugins/plugingen — do not edit by hand.
// Regenerate with `make plugins-build`; CI gate: `make verify-plugins-build`.
//
// This is the MCP entry internal/mcp's Registrar writes into
// ~/.config/opencode/opencode.json for `observer init --opencode`, read back
// out of a sandbox HOME and transposed verbatim. The one deviation is the
// binary: a published package cannot know an absolute install path, so the
// generator drives the registrar with the PATH name.

/** The stable MCP server id observer registers under. */
export const OBSERVER_MCP_SERVER_NAME = "observer";

/** OpenCode's McpLocalConfig entry for the observer MCP server. */
export const OBSERVER_MCP_SERVER = {
  type: "local" as const,
  command: ["observer", "serve"],
  enabled: true,
};
