#!/usr/bin/env bash
# assemble-plugins-repo.sh — build the PUBLIC `superbasedapp/plugins`
# repository tree from the committed plugins/ directory.
#
#   scripts/assemble-plugins-repo.sh <output-dir> <version>
#   scripts/assemble-plugins-repo.sh --self-check [version]
#
# <version> is REQUIRED for an assembly run — there is no default. See
# "VERSION" below for why.
#
# plugins/ is the in-tree source of truth (generated by plugins/plugingen,
# which RUNS the real `observer init` registrars — see
# scripts/verify-plugins-build.sh). It is laid out one directory per
# surface, which is right for a subdirectory of this repo and WRONG for
# the public repo: every plugin format resolves its relative paths from a
# REPOSITORY ROOT.
#
#   - Claude Code wants .claude-plugin/marketplace.json at the root, so
#     its entry's "./<dir>" source resolves.
#   - Codex wants .agents/plugins/marketplace.json at the root, so its
#     entry's "./plugins/<dir>" source resolves.
#   - Gemini CLI wants gemini-extension.json at the root: `gemini
#     extensions install <github-url>` documents a repo or a local path
#     and NOTHING ELSE — installing from a repo SUBDIRECTORY is not
#     documented anywhere, so root placement is required, not preferred.
#     Root placement also serves qwen-code, whose docs state that
#     `qwen extensions install <owner>/<repo>` auto-converts a
#     gemini-extension.json.
#
# ROOT PLACEMENT, DECIDED PER VENDOR (coverage waves A-C, plan §7). The
# rule is the vendor's own documented INSTALL MECHANISM, not symmetry:
# a surface goes to the root if and only if some documented install
# resolves it FROM a repository root.
#
#   ROOT, because the install takes a repo URL / owner-repo:
#     * kimi.plugin.json          — `/plugins install <github-url>`
#     * openclaw.plugin.json      — `openclaw plugins install <git spec>`
#     * .devin-plugin/plugin.json (+ its sibling mcp_config.json)
#                                 — `devin plugins install acme/repo`
#     * .factory-plugin/marketplace.json + the plugin it names
#                                 — `droid plugin marketplace add <src>`.
#       Droid ALSO documents `.claude-plugin/marketplace.json` as a
#       FALLBACK, so a repo carrying only the Claude catalog would answer
#       a Droid marketplace-add with the CLAUDE plugin — hooks and all.
#       Shipping our own catalog at the root shadows that fallback with a
#       plugin that declares only an MCP server. Its plugin directory is
#       nested (`factory/<plugin>`) precisely so it does not merge with
#       the Claude Code plugin directory; see plugins/plugingen/droid.go.
#
#     * .qoder-plugin/marketplace.json — `qodercli plugins marketplace add
#       <source>` reads the catalog from the root, in the order
#       `.qoder-plugin/marketplace.json` → `.claude-plugin/marketplace.json`
#       → `marketplace.json`. Qoder therefore falls through to the CLAUDE
#       catalog when ours is absent — the identical trap Droid documents,
#       verified live against qodercli 1.1.5 (a marketplace-add of an
#       assembled tree without this file installed the Claude Code plugin,
#       hooks and all). Only the CATALOG goes to the root; its plugin stays
#       at `qoder/<plugin>`, which is what its `./qoder/<plugin>` source
#       names.
#
#   SUBDIRECTORY, because nothing resolves from a root:
#     * qoder/<plugin>/ — `qodercli plugins install <local path>` is the
#                      documented direct install; only its catalog (above)
#                      needs the root.
#     * antigravity/ — `agy plugin install <local dir>` stages into the
#                      user's own home. COMMITTED DECISION, and it also
#                      keeps `.agents/plugins/` (Codex's) untouched.
#     * cowork/      — you pack the directory into a .mcpb; nothing reads
#                      it from a repo root.
#     * copilot/     — a one-click URI, not a file a tool reads.
#     * every wave-B config listing (crush, kiro-cli, copilot-cli,
#       kilo-code, roo-code, open-interpreter) and the two no-package
#       decisions (pi, command-code) — READMEs carrying a config block.
#
# None of the root-level names collide, which is what makes ONE repo root
# able to carry all of them; each vendor reads only the file it names.
# This script performs that transpose deterministically instead of by
# hand.
#
# GUARANTEES
#   * NEVER mutates the working tree. It only writes under <output-dir>
#     (and, for --self-check, under two mktemp dirs it removes itself).
#   * NO SYMLINKS, in or out. Every source path this script copies is
#     scanned before the copy, and the assembled tree is scanned after it;
#     a single symlink anywhere is a hard failure. `cp -r` PRESERVES
#     symlinks, and two later steps follow what they are handed: the
#     version stamper opens each manifest for writing (a symlinked
#     manifest would write OUTSIDE the output dir), and the honesty scan
#     walks regular files (a symlinked README would carry unscanned prose
#     into a published listing). Refusing them outright is the one check
#     that closes both.
#   * Deterministic: the same inputs produce a byte-identical tree.
#     `--self-check` proves it by assembling twice and diffing.
#   * Publishes nothing. There is no git, no npm, no network here.
#
# WHAT IS *NOT* HERE
#   plugins/README.md (the in-tree index) is deliberately excluded: it
#   documents this repository's generation flow, not the public artifact.
#   The root README this script writes replaces it.
#
# OPENCODE SOURCE — INCLUDED, on purpose.
#   The npm package `@superbased/opencode-plugin` is distributed through
#   npm, not through this repo, so including its source is a choice. It is
#   included because the package's own package.json declares
#   `repository.url = github.com/superbasedapp/plugins` with
#   `repository.directory = "opencode"` — npm renders that as a source
#   link on the package page. Shipping the manifest without the directory
#   it points at would publish a dangling claim. `dist/` and
#   `node_modules/` are NOT included (build artefacts; `npm run build`
#   produces them at publish time).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/plugins"

# VERSION — REQUIRED, never defaulted, never derived.
#
# A public plugin manifest's version is a pin users install against, so it
# must name a release whose binary actually exists. There are three ways to
# get it and only one is honest:
#
#   * A hard-coded default goes stale silently the moment the next tag
#     ships — it was `1.27.0`, and after v1.28.0 a versionless run would
#     have published v1.27.0 manifests while claiming to be current. That
#     is why there is no default any more.
#   * DERIVING it from npm/observer/package.json is WORSE, not better:
#     that file carries the UNRELEASED next version (it is stamped at
#     release-prep time and is routinely ahead of the last tag), so
#     deriving would publish manifests pinned to a release that does not
#     exist yet and send every installer at a missing binary. Do not
#     "improve" this by reading it.
#   * The operator names the tag they are publishing. That is the only
#     value that is true by construction.
#
# --self-check is the exception, and it says so out loud: it assembles
# twice into mktemp dirs to prove determinism and publishes nothing, so it
# uses the explicitly-labelled fixture below when no version is given.
SELF_CHECK_FIXTURE_VERSION="0.0.0-selfcheck"

# THE prerequisite sentence, verbatim. It is the exported
# `binaryPrereqSentence` constant in plugins/plugingen — the single source
# every manifest description and every README carries. Hard-coding it here
# (it is interpolated into the root README this script authors) is safe
# ONLY because of the honesty gate at the bottom, whose README half runs
# inside plugingen against the Go constant: if plugingen's sentence changes
# and this copy does not, the assembled root README no longer carries the
# real sentence and assembly FAILS.
PREREQ_SENTENCE='Requires the `observer` binary already on your PATH'

# The banned-claim list used to live here, as a literal-phrase array. It
# is GONE on purpose: it was the weaker half of the rule, and the one file
# it exclusively gated was the root README this script authors itself — so
# "cuts context usage by 40%" (no banned phrase in it anywhere) would have
# passed on the landing page while plugingen's tests rejected the same
# sentence everywhere else.
#
# There is now ONE checker, in Go, owned by plugins/plugingen/honesty.go:
# literal phrases AND the pattern class (a percentage figure standing
# within 80 characters of token/context/cost/usage vocabulary) AND the
# verbatim prerequisite sentence in every README. plugingen's tests run it
# over the generated tree; honesty_gate below runs the SAME code over the
# FINAL assembled tree via `plugingen -honesty-check`.

die() { echo "assemble-plugins-repo: $*" >&2; exit 1; }

# ---------------------------------------------------------------------
# Argument handling
# ---------------------------------------------------------------------

SELF_CHECK=0
if [ "${1:-}" = "--self-check" ]; then
    SELF_CHECK=1
    shift
    OUT_DIR=""
    RAW_VERSION="${1:-$SELF_CHECK_FIXTURE_VERSION}"
else
    [ "$#" -ge 2 ] || die "usage: $0 <output-dir> <version>
       $0 --self-check [version]
the version is REQUIRED and is the RELEASE TAG you are publishing — there is
no default, and it is deliberately NOT derived from npm/observer/package.json
(that file carries the unreleased next version)"
    OUT_DIR="$1"
    RAW_VERSION="$2"
    shift 2
fi

# Validate through sync-npm-version.sh's STRICT SemVer 2.0.0 gate rather
# than a second copy of semver.org's regex. One owner: a string this
# script accepts is exactly a string the release stamp accepts, so a
# mistyped tag cannot pass here and fail at `npm publish` or at Codex's
# plugin validator (which requires strict semver). --validate-only writes
# nothing and echoes the leading-'v'-stripped version.
VERSION="$("$REPO_ROOT/scripts/sync-npm-version.sh" --validate-only "$RAW_VERSION")"

# ---------------------------------------------------------------------
# Derive the plugin directory names from the catalogs themselves.
#
# One-owner discipline: internal/claudeplugin names the plugin,
# plugins/plugingen stamps that name into both marketplace manifests, and
# this script READS it back out of them. A rename therefore reaches the
# public layout automatically instead of needing a matching edit here.
# ---------------------------------------------------------------------

CLAUDE_MARKETPLACE="$SRC/claude-code/.claude-plugin/marketplace.json"
CODEX_MARKETPLACE="$SRC/codex/.agents/plugins/marketplace.json"
DROID_MARKETPLACE="$SRC/droid/.factory-plugin/marketplace.json"
QODER_MARKETPLACE="$SRC/qoder/.qoder-plugin/marketplace.json"
[ -f "$CLAUDE_MARKETPLACE" ] || die "missing $CLAUDE_MARKETPLACE"
[ -f "$CODEX_MARKETPLACE" ] || die "missing $CODEX_MARKETPLACE"
[ -f "$DROID_MARKETPLACE" ] || die "missing $DROID_MARKETPLACE"
[ -f "$QODER_MARKETPLACE" ] || die "missing $QODER_MARKETPLACE"

CLAUDE_PLUGIN_DIR="$(node -e '
const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
const src = (m.plugins || []).map(p => p.source).filter(s => typeof s === "string");
if (src.length !== 1) { console.error("want exactly one string source, got " + JSON.stringify(src)); process.exit(1); }
if (!src[0].startsWith("./") || src[0].includes("..")) { console.error("source must be a \"./\"-relative path that never escapes the root: " + src[0]); process.exit(1); }
process.stdout.write(src[0].slice(2));
' "$CLAUDE_MARKETPLACE")" || die "could not read the Claude Code catalog source"

CODEX_PLUGIN_PATH="$(node -e '
const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
const src = (m.plugins || []).map(p => p.source && p.source.path).filter(Boolean);
if (src.length !== 1) { console.error("want exactly one source.path, got " + JSON.stringify(src)); process.exit(1); }
if (!src[0].startsWith("./") || src[0].includes("..")) { console.error("source.path must be a \"./\"-relative path that never escapes the root: " + src[0]); process.exit(1); }
process.stdout.write(src[0].slice(2));
' "$CODEX_MARKETPLACE")" || die "could not read the Codex catalog source"

DROID_PLUGIN_PATH="$(node -e '
const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
const src = (m.plugins || []).map(p => p.source).filter(s => typeof s === "string");
if (src.length !== 1) { console.error("want exactly one string source, got " + JSON.stringify(src)); process.exit(1); }
if (!src[0].startsWith("./") || src[0].includes("..")) { console.error("source must be a \"./\"-relative path that never escapes the root: " + src[0]); process.exit(1); }
process.stdout.write(src[0].slice(2));
' "$DROID_MARKETPLACE")" || die "could not read the Droid catalog source"

# The Qoder catalog is the one whose source is written against the
# ASSEMBLED root from a surface subdirectory: `./qoder/<plugin>`. In this
# tree that means it resolves against plugins/ itself, which is why the
# existence check below is "$SRC/$QODER_PLUGIN_PATH" rather than
# "$SRC/qoder/$QODER_PLUGIN_PATH". See plugins/plugingen/qoder.go.
QODER_PLUGIN_PATH="$(node -e '
const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
const src = (m.plugins || []).map(p => p.source).filter(s => typeof s === "string");
if (src.length !== 1) { console.error("want exactly one string source, got " + JSON.stringify(src)); process.exit(1); }
if (!src[0].startsWith("./") || src[0].includes("..")) { console.error("source must be a \"./\"-relative path that never escapes the root: " + src[0]); process.exit(1); }
process.stdout.write(src[0].slice(2));
' "$QODER_MARKETPLACE")" || die "could not read the Qoder catalog source"

[ -d "$SRC/claude-code/$CLAUDE_PLUGIN_DIR" ] \
    || die "the Claude catalog points at ./$CLAUDE_PLUGIN_DIR, which does not exist under plugins/claude-code/"
[ -d "$SRC/codex/$CODEX_PLUGIN_PATH" ] \
    || die "the Codex catalog points at ./$CODEX_PLUGIN_PATH, which does not exist under plugins/codex/"
[ -d "$SRC/droid/$DROID_PLUGIN_PATH" ] \
    || die "the Droid catalog points at ./$DROID_PLUGIN_PATH, which does not exist under plugins/droid/"
[ -d "$SRC/$QODER_PLUGIN_PATH" ] \
    || die "the Qoder catalog points at ./$QODER_PLUGIN_PATH, which does not exist under plugins/"

# The Droid plugin directory must not land on top of another vendor's.
# plugins/plugingen/droid.go nests it under factory/ for exactly this
# reason (the Claude Code plugin directory carries a hooks/hooks.json
# written for claude-code); assert it here too, because THIS script is
# where the three would actually collide on disk.
case "$DROID_PLUGIN_PATH" in
    "$CLAUDE_PLUGIN_DIR"|"$CLAUDE_PLUGIN_DIR"/*|"$CODEX_PLUGIN_PATH"|"$CODEX_PLUGIN_PATH"/*)
        die "the Droid catalog points at ./$DROID_PLUGIN_PATH, which collides with another vendor's plugin directory at the repository root" ;;
esac
case "$CLAUDE_PLUGIN_DIR" in
    "$DROID_PLUGIN_PATH"/*) die "the Claude plugin directory nests inside the Droid one" ;;
esac

# Same rule for Qoder's, checked against all three of the others. Qoder's
# plugin is the one that stays in a subdirectory, so this is expected to
# hold trivially — which is exactly why it is asserted rather than assumed:
# the day someone "simplifies" the catalog source to ./<plugin>, the Qoder
# marketplace would start resolving the Claude Code plugin, which is the
# whole failure this catalog exists to prevent.
for other in "$CLAUDE_PLUGIN_DIR" "$CODEX_PLUGIN_PATH" "$DROID_PLUGIN_PATH"; do
    case "$QODER_PLUGIN_PATH" in
        "$other"|"$other"/*)
            die "the Qoder catalog points at ./$QODER_PLUGIN_PATH, which collides with another vendor's plugin directory at the repository root" ;;
    esac
    case "$other" in
        "$QODER_PLUGIN_PATH"/*)
            die "another vendor's plugin directory ($other) nests inside the Qoder one" ;;
    esac
done

# plugingen names every surface's plugin directory from ONE constant
# (internal/claudeplugin.Dir). The Claude catalog is the one that
# publishes it, so it is read back from there and reused for the surfaces
# that carry no catalog of their own (qoder, cowork, antigravity).
PLUGIN_DIR="$CLAUDE_PLUGIN_DIR"
for surface_plugin in "qoder/$PLUGIN_DIR" "cowork/$PLUGIN_DIR" "antigravity/$PLUGIN_DIR" "kimi-code/$PLUGIN_DIR" "devin/$PLUGIN_DIR" "openclaw/$PLUGIN_DIR"; do
    [ -d "$SRC/$surface_plugin" ] \
        || die "expected a plugin directory at plugins/$surface_plugin (plugingen names them all after the one plugin id)"
done

OPENCODE_PKG_NAME="$(node -e '
process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1], "utf8")).name);
' "$SRC/opencode/package.json")" || die "could not read the OpenCode package name"

# ---------------------------------------------------------------------
# refuse_symlinks <label> <path>... — hard-fail if any path IS a symlink
# or CONTAINS one at any depth.
#
# `find` does not follow symlinks by default, so `-type l` reports the
# link itself rather than what it points at, which is exactly what we
# want to name in the error.
#
# Called twice: once over the exact set of source paths that get copied
# (before the copy), once over the assembled tree (after the copy, before
# anything writes to or scans it). See the GUARANTEES block at the top for
# the two concrete escapes this closes.
# ---------------------------------------------------------------------

refuse_symlinks() {
    local label="$1"
    shift
    local links
    links="$(find "$@" -type l -print 2>/dev/null || true)"
    if [ -n "$links" ]; then
        echo "assemble-plugins-repo: symlink(s) found in $label:" >&2
        echo "$links" | sed 's/^/  /' >&2
        die "symlinks are refused: cp -r preserves them, the version stamper would follow one out of the output directory, and a symlinked README evades the honesty scan"
    fi
}

# The exact source paths assemble() copies. Enumerated (rather than
# scanning all of plugins/) so a developer's plugins/opencode/node_modules
# — full of legitimate npm .bin symlinks, and never copied — cannot fail a
# release run.
SOURCE_PATHS=(
    "$CLAUDE_MARKETPLACE"
    "$SRC/claude-code/$CLAUDE_PLUGIN_DIR"
    "$CODEX_MARKETPLACE"
    "$SRC/codex/$CODEX_PLUGIN_PATH"
    "$SRC/codex/README.md"
    "$SRC/gemini/gemini-extension.json"
    "$SRC/gemini/README.md"
    "$SRC/goose/README.md"
    "$SRC/cursor/README.md"
    "$SRC/cursor/deeplink.txt"
    "$SRC/opencode/package.json"
    "$SRC/opencode/tsconfig.json"
    "$SRC/opencode/README.md"
    "$SRC/opencode/src"

    # -- coverage wave A: manifest surfaces -------------------------
    "$SRC/kimi-code/$PLUGIN_DIR"
    "$SRC/kimi-code/README.md"
    "$QODER_MARKETPLACE"
    "$SRC/$QODER_PLUGIN_PATH"
    "$SRC/qoder/README.md"
    "$SRC/devin/$PLUGIN_DIR"
    "$SRC/devin/README.md"
    "$DROID_MARKETPLACE"
    "$SRC/droid/$DROID_PLUGIN_PATH"
    "$SRC/droid/README.md"
    "$SRC/openclaw/$PLUGIN_DIR"
    "$SRC/openclaw/README.md"
    "$SRC/antigravity/$PLUGIN_DIR"
    "$SRC/antigravity/README.md"

    # -- coverage wave B: config listings (README only) -------------
    "$SRC/crush/README.md"
    "$SRC/kiro-cli/README.md"
    "$SRC/copilot-cli/README.md"
    "$SRC/kilo-code/README.md"
    "$SRC/roo-code/README.md"
    "$SRC/open-interpreter/README.md"

    # -- coverage wave C: special formats + the two no-package rows -
    "$SRC/copilot/install-uri.txt"
    "$SRC/copilot/README.md"
    "$SRC/cowork/$PLUGIN_DIR"
    "$SRC/cowork/README.md"
    "$SRC/pi/README.md"
    "$SRC/command-code/README.md"

    "$REPO_ROOT/LICENSE"
)

refuse_symlinks "the selected source tree" "${SOURCE_PATHS[@]}"

# ---------------------------------------------------------------------
# UNSHIPPED_PATTERNS — every file under plugins/ that is deliberately NOT
# published, as shell glob patterns relative to plugins/.
#
# This list is the OTHER half of SOURCE_PATHS. SOURCE_PATHS enumerates
# what gets copied; without a complementary "and nothing else exists"
# rule, adding a surface to plugins/ and forgetting to add it here
# produces a public tree that is silently missing it — which is exactly
# what happened to the whole coverage-wave set once already. Together the
# two lists must cover plugins/ exactly, and assert_source_completeness
# below fails if they do not.
#
# Each entry is a decision, not a convenience:
#   README.md        — the in-tree index. It documents this repository's
#                      generation flow, not the public artifact, and
#                      write_root_readme authors a replacement.
#   plugingen/*      — the generator itself. Go source for a private repo.
#   opencode/node_modules/*, opencode/dist/*, opencode/package-lock.json
#                    — local build/install artefacts of the npm package;
#                      `npm run build` produces dist/ at publish time.
# ---------------------------------------------------------------------
UNSHIPPED_PATTERNS=(
    "README.md"
    "plugingen/*"
    "opencode/node_modules/*"
    "opencode/dist/*"
    "opencode/package-lock.json"
)

# ---------------------------------------------------------------------
# assert_source_completeness — every file under plugins/ is either copied
# (SOURCE_PATHS) or explicitly unshipped (UNSHIPPED_PATTERNS).
#
# Run from --self-check only, which is the CI gate. It is deliberately NOT
# on the assembly path: an operator's scratch file under plugins/ should
# not block a publish, and CI has already refused the merge that would
# have introduced a real gap.
# ---------------------------------------------------------------------

assert_source_completeness() {
    local covered present rel pattern unshipped missing

    covered="$(
        for p in "${SOURCE_PATHS[@]}"; do
            # LICENSE is copied from the repository root, not from plugins/.
            case "$p" in
                "$SRC"/*) find "$p" -type f -print ;;
            esac
        done | sed "s|^$SRC/||" | sort -u
    )"

    present="$(cd "$SRC" && find . -type f | sed 's|^\./||' | sort)"

    missing=""
    while IFS= read -r rel; do
        [ -n "$rel" ] || continue
        unshipped=0
        for pattern in "${UNSHIPPED_PATTERNS[@]}"; do
            # shellcheck disable=SC2254 # the patterns ARE globs, on purpose
            case "$rel" in
                $pattern) unshipped=1; break ;;
            esac
        done
        [ "$unshipped" -eq 0 ] || continue
        printf '%s\n' "$covered" | grep -Fxq -- "$rel" && continue
        missing="$missing  plugins/$rel"$'\n'
    done <<EOF
$present
EOF

    if [ -n "$missing" ]; then
        echo "assemble-plugins-repo: these files exist under plugins/ but are neither copied nor listed as intentionally unshipped:" >&2
        printf '%s' "$missing" >&2
        die "add them to SOURCE_PATHS (and to assemble()) or to UNSHIPPED_PATTERNS — a public tree that silently drops a surface is the failure this check exists for"
    fi

    echo "assemble-plugins-repo: source completeness — every file under plugins/ is either copied or explicitly unshipped"
}

# ---------------------------------------------------------------------
# Section extraction — the root README is ASSEMBLED from the per-surface
# READMEs rather than re-typed, so an install command can never drift
# between the landing page and the surface that owns it.
#
# Each surface declares an exact START heading and an exact END heading;
# the block between them (START inclusive, END exclusive) is copied
# VERBATIM. Both anchors must exist and be in order, otherwise assembly
# fails loudly — a silently-empty install section on the landing page is
# exactly the failure this guard exists to prevent.
#
# The ONE transformation applied to the copied text: ATX headings are
# demoted two levels, so a surface's `## Install` nests under the landing
# page's `### <Surface>` instead of colliding with the page's own H2s.
# Headings INSIDE fenced code blocks are left alone (a `# comment` line in
# a bash example is not a heading), which is what the fence toggle is for.
# Prose is untouched — the honesty sentences are copied byte for byte.
# ---------------------------------------------------------------------

extract_section() {
    local file="$1" start="$2" end="$3"
    [ -f "$file" ] || die "missing README $file"
    grep -Fxq -- "$start" "$file" || die "$file has no '$start' heading (README structure changed)"
    grep -Fxq -- "$end" "$file" || die "$file has no '$end' heading (README structure changed)"
    local start_line end_line
    start_line=$(grep -Fxn -- "$start" "$file" | head -1 | cut -d: -f1)
    end_line=$(grep -Fxn -- "$end" "$file" | head -1 | cut -d: -f1)
    [ "$start_line" -lt "$end_line" ] || die "$file: '$start' does not precede '$end'"
    awk -v s="$start_line" -v e="$end_line" '
        NR < s || NR >= e { next }
        /^```/ { fence = !fence; print; next }
        !fence && /^#+ / {
            n = 0
            while (substr($0, n + 1, 1) == "#") n++
            if (n + 2 <= 6) { print "##" $0; next }
        }
        { print }
    ' "$file"
}

# ---------------------------------------------------------------------
# assemble <output-dir>
# ---------------------------------------------------------------------

assemble() {
    local out="$1"

    if [ -e "$out" ]; then
        [ -d "$out" ] || die "$out exists and is not a directory"
        [ -z "$(ls -A "$out")" ] || die "$out is not empty — refusing to clobber it"
    fi
    mkdir -p "$out"
    out="$(cd "$out" && pwd)"

    # -- Claude Code: catalog at the root, plugin beneath it -----------
    mkdir -p "$out/.claude-plugin"
    cp "$CLAUDE_MARKETPLACE" "$out/.claude-plugin/marketplace.json"
    cp -r "$SRC/claude-code/$CLAUDE_PLUGIN_DIR" "$out/$CLAUDE_PLUGIN_DIR"

    # -- Codex: catalog at the root, plugin at the catalog's path ------
    mkdir -p "$out/.agents/plugins" "$out/$(dirname "$CODEX_PLUGIN_PATH")"
    cp "$CODEX_MARKETPLACE" "$out/.agents/plugins/marketplace.json"
    cp -r "$SRC/codex/$CODEX_PLUGIN_PATH" "$out/$CODEX_PLUGIN_PATH"
    mkdir -p "$out/codex"
    cp "$SRC/codex/README.md" "$out/codex/README.md"

    # -- Gemini CLI: manifest at the root (subdir installs undocumented)
    cp "$SRC/gemini/gemini-extension.json" "$out/gemini-extension.json"
    mkdir -p "$out/gemini"
    cp "$SRC/gemini/README.md" "$out/gemini/README.md"

    # -- Goose: no manifest exists; the README carries the config block -
    mkdir -p "$out/goose"
    cp "$SRC/goose/README.md" "$out/goose/README.md"

    # -- Cursor: the static deeplink + its security note ----------------
    mkdir -p "$out/cursor"
    cp "$SRC/cursor/README.md" "$out/cursor/README.md"
    cp "$SRC/cursor/deeplink.txt" "$out/cursor/deeplink.txt"

    # -- OpenCode: the npm package source (see the header note) ---------
    mkdir -p "$out/opencode"
    cp "$SRC/opencode/package.json" "$SRC/opencode/tsconfig.json" \
       "$SRC/opencode/README.md" "$out/opencode/"
    cp -r "$SRC/opencode/src" "$out/opencode/src"

    # -- coverage wave A: ROOT-placed manifests -------------------------
    # Kimi installs from a repository URL, so its manifest is the repo's.
    cp "$SRC/kimi-code/$PLUGIN_DIR/kimi.plugin.json" "$out/kimi.plugin.json"
    mkdir -p "$out/kimi-code"
    cp "$SRC/kimi-code/README.md" "$out/kimi-code/README.md"

    # OpenClaw installs from a git spec, so its manifest is the repo's.
    cp "$SRC/openclaw/$PLUGIN_DIR/openclaw.plugin.json" "$out/openclaw.plugin.json"
    mkdir -p "$out/openclaw"
    cp "$SRC/openclaw/README.md" "$out/openclaw/README.md"

    # Devin installs from owner/repo or a git URL: the plugin ROOT is the
    # repository root, so both the manifest directory and its sibling
    # component file land at the top.
    mkdir -p "$out/.devin-plugin" "$out/devin"
    cp "$SRC/devin/$PLUGIN_DIR/.devin-plugin/plugin.json" "$out/.devin-plugin/plugin.json"
    cp "$SRC/devin/$PLUGIN_DIR/mcp_config.json" "$out/mcp_config.json"
    cp "$SRC/devin/README.md" "$out/devin/README.md"

    # Droid: catalog at the root (it shadows the .claude-plugin fallback),
    # plugin at the catalog's own nested path.
    mkdir -p "$out/.factory-plugin" "$out/$(dirname "$DROID_PLUGIN_PATH")" "$out/droid"
    cp "$DROID_MARKETPLACE" "$out/.factory-plugin/marketplace.json"
    cp -r "$SRC/droid/$DROID_PLUGIN_PATH" "$out/$DROID_PLUGIN_PATH"
    cp "$SRC/droid/README.md" "$out/droid/README.md"

    # -- coverage wave A: SUBDIRECTORY surfaces -------------------------
    # Qoder installs from a local path; Antigravity stages a local
    # directory into the user's own home. Neither PLUGIN resolves anything
    # from a repository root, and Antigravity deliberately stays out of
    # .agents/plugins/ (Codex's).
    #
    # Qoder's CATALOG is the exception and does go to the root: Qoder's
    # marketplace loader falls back to .claude-plugin/marketplace.json,
    # so without ours a `qodercli plugins marketplace add` on this repo
    # resolves the Claude Code plugin — hooks written for another tool
    # included. Ours takes the first slot and points at ./qoder/<plugin>.
    mkdir -p "$out/.qoder-plugin" "$out/$(dirname "$QODER_PLUGIN_PATH")" "$out/antigravity"
    cp "$QODER_MARKETPLACE" "$out/.qoder-plugin/marketplace.json"
    cp -r "$SRC/$QODER_PLUGIN_PATH" "$out/$QODER_PLUGIN_PATH"
    cp "$SRC/qoder/README.md" "$out/qoder/README.md"
    cp -r "$SRC/antigravity/$PLUGIN_DIR" "$out/antigravity/$PLUGIN_DIR"
    cp "$SRC/antigravity/README.md" "$out/antigravity/README.md"

    # -- coverage wave B: config listings (README only) -----------------
    local listing
    for listing in crush kiro-cli copilot-cli kilo-code roo-code open-interpreter; do
        mkdir -p "$out/$listing"
        cp "$SRC/$listing/README.md" "$out/$listing/README.md"
    done

    # -- coverage wave C ------------------------------------------------
    mkdir -p "$out/copilot" "$out/cowork" "$out/pi" "$out/command-code"
    cp "$SRC/copilot/README.md" "$out/copilot/README.md"
    cp "$SRC/copilot/install-uri.txt" "$out/copilot/install-uri.txt"
    cp -r "$SRC/cowork/$PLUGIN_DIR" "$out/cowork/$PLUGIN_DIR"
    cp "$SRC/cowork/README.md" "$out/cowork/README.md"
    cp "$SRC/pi/README.md" "$out/pi/README.md"
    cp "$SRC/command-code/README.md" "$out/command-code/README.md"

    cp "$REPO_ROOT/LICENSE" "$out/LICENSE"

    cat > "$out/.gitignore" <<'GITIGNORE'
# Build artefacts of the OpenCode npm package. `npm run build` produces
# dist/ at publish time; neither it nor node_modules/ is committed.
node_modules/
dist/
GITIGNORE

    # Before ANYTHING writes to or reads through the assembled paths. The
    # source scan above cannot cover this on its own: `cp -r` of a clean
    # tree cannot create a link, but the output directory is caller-
    # supplied and only asserted to be empty, so this is the check that
    # holds for the tree the stamper and the honesty scan actually see.
    refuse_symlinks "the assembled tree" "$out"

    stamp_versions "$out"
    write_root_readme "$out"
    honesty_gate "$out"
}

# ---------------------------------------------------------------------
# stamp_versions — restamp EVERY version-bearing manifest in the
# ASSEMBLED tree. The source tree is never touched.
#
# The same manifests scripts/sync-npm-version.sh stamps, at their
# assembled paths, with the same Node in-place edit (2-space indent, one
# trailing newline, existing keys only) so the result stays byte-identical
# to what plugingen would emit for that version. Eleven in total: the
# original five plus the coverage waves' kimi / openclaw / devin / droid /
# qoder manifests and the Claude Desktop .mcpb manifest.
#
# Deliberately ABSENT, each because there is no version field to stamp:
# the Codex, Droid and Qoder *marketplace* catalogs (a `local`/relative
# source entry has no version — the plugin's own manifest is the pin, which
# for Qoder was confirmed live: `qodercli plugins list` printed the
# plugin-manifest version for a catalog entry that carried none) and
# Antigravity's plugin.json (its documented schema has exactly one field,
# `name`). assert_every_version_field below is the backstop that catches a
# manifest this list has never heard of.
# ---------------------------------------------------------------------

stamp_versions() {
    local out="$1"

    for manifest in \
        "$out/$CLAUDE_PLUGIN_DIR/.claude-plugin/plugin.json" \
        "$out/gemini-extension.json" \
        "$out/$CODEX_PLUGIN_PATH/.codex-plugin/plugin.json" \
        "$out/opencode/package.json" \
        "$out/kimi.plugin.json" \
        "$out/openclaw.plugin.json" \
        "$out/.devin-plugin/plugin.json" \
        "$out/$DROID_PLUGIN_PATH/.factory-plugin/plugin.json" \
        "$out/$QODER_PLUGIN_PATH/.qoder-plugin/plugin.json" \
        "$out/cowork/$PLUGIN_DIR/manifest.json"
    do
        [ -f "$manifest" ] || die "expected a version-bearing manifest at $manifest"
        node - "$manifest" "$VERSION" <<'EOF'
const fs = require('fs');
const [, , filePath, version] = process.argv;
const doc = JSON.parse(fs.readFileSync(filePath, 'utf8'));
if (doc.version === undefined) {
  console.error(`${filePath} has no version field to stamp`);
  process.exit(1);
}
doc.version = version;
fs.writeFileSync(filePath, JSON.stringify(doc, null, 2) + '\n');
EOF
    done

    node - "$out/.claude-plugin/marketplace.json" "$VERSION" <<'EOF'
const fs = require('fs');
const [, , filePath, version] = process.argv;
const manifest = JSON.parse(fs.readFileSync(filePath, 'utf8'));
// Stamp every catalog entry that already carries a version. An entry
// WITHOUT one is deliberately pinned to its git SHA (Claude Code's
// commit-SHA versioning mode), so don't invent a version for it.
let stamped = 0;
for (const entry of manifest.plugins || []) {
  if (entry.version) { entry.version = version; stamped++; }
}
if (stamped === 0) {
  console.error(`${filePath}: no catalog entry carried a version to stamp`);
  process.exit(1);
}
fs.writeFileSync(filePath, JSON.stringify(manifest, null, 2) + '\n');
EOF

    assert_every_version_field "$out"
}

# ---------------------------------------------------------------------
# assert_every_version_field — UNCONDITIONALLY enumerate every
# version-bearing field in the assembled tree and require each to equal
# VERSION exactly.
#
# This replaced a guard that grepped for the ONE in-tree source version and
# skipped itself entirely when that happened to equal VERSION. Both halves
# were bypasses: a new surface's manifest carrying any OTHER version (a
# hand-pinned "0.1.0", a stale copy) was invisible, and assembling at the
# in-tree version disabled the check altogether. The rule here does not
# depend on what the source tree carried:
#
#   * every *.json file is walked STRUCTURALLY, at any depth, and every
#     string-valued key named "version" must equal VERSION — that is what
#     catches a manifest stamp_versions has never heard of;
#   * every file, JSON or not, is additionally scanned for a literal
#     `"version": "…"` / `version = "…"` / `version: "…"` assignment, so a
#     version constant in a .ts / .yaml / .toml surface is caught too.
#
# Dependency RANGES are not version fields: they live under keys named
# after the package ("typescript": "^5.7.2"), so the structural rule never
# sees them.
# ---------------------------------------------------------------------

assert_every_version_field() {
    local out="$1"
    node - "$out" "$VERSION" <<'EOF'
const fs = require('fs');
const path = require('path');
const [, , root, version] = process.argv;

const problems = [];
let fields = 0;

// Structural: any string-valued "version" key, at any depth.
function walkJSON(node, file, pointer) {
  if (Array.isArray(node)) {
    node.forEach((v, i) => walkJSON(v, file, `${pointer}/${i}`));
    return;
  }
  if (node === null || typeof node !== 'object') return;
  for (const [key, value] of Object.entries(node)) {
    const here = `${pointer}/${key}`;
    if (key === 'version' && typeof value === 'string') {
      fields++;
      if (value !== version) {
        problems.push(`${file}${here} = "${value}", want "${version}"`);
      }
      continue;
    }
    walkJSON(value, file, here);
  }
}

// Textual: a version assignment in any file, including non-JSON ones —
// `version: "…"` (YAML/TOML) and `PLUGIN_VERSION = "…"` (a TS constant)
// alike. The optional identifier prefix must end in `_`, `.` or `$` so
// that words merely ENDING in "version" (conversion: "auto") are not
// mistaken for one.
const assignment = /(?:^|[^A-Za-z0-9])(?:[A-Za-z0-9_$]*[_.$])?version["']?\s*[:=]\s*"([^"\n]{1,64})"/gi;

function walkDir(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) { walkDir(full); continue; }
    if (!entry.isFile()) continue;
    const rel = path.relative(root, full);
    const body = fs.readFileSync(full, 'utf8');
    if (entry.name.endsWith('.json')) {
      let doc;
      try {
        doc = JSON.parse(body);
      } catch (err) {
        problems.push(`${rel}: is not valid JSON (${err.message})`);
        continue;
      }
      walkJSON(doc, rel, '');
      continue;
    }
    for (const m of body.matchAll(assignment)) {
      fields++;
      if (m[1] !== version) {
        problems.push(`${rel}: carries a version assignment "${m[1]}", want "${version}"`);
      }
    }
  }
}

walkDir(root);

if (fields === 0) {
  console.error('assemble-plugins-repo: the assembled tree carries NO version field at all — the restamp cannot have worked');
  process.exit(1);
}
if (problems.length > 0) {
  console.error('assemble-plugins-repo: version fields disagree with the assembled version ' + version + ':');
  for (const p of problems) console.error('  ' + p);
  console.error('teach stamp_versions about the file(s) above, or fix the source manifest');
  process.exit(1);
}
EOF
}

# ---------------------------------------------------------------------
# write_root_readme — the landing page.
#
# Its install blocks are EXTRACTED from the per-surface READMEs, not
# re-typed, so the landing page cannot drift from the surface that owns
# the command.
# ---------------------------------------------------------------------

write_root_readme() {
    local out="$1"
    local readme="$out/README.md"

    {
        cat <<EOF
<!-- ASSEMBLED by scripts/assemble-plugins-repo.sh in the superbased-observer
     repository. Do not edit by hand: the per-surface sections below are
     copied verbatim out of each surface's own README, which is itself
     generated by plugins/plugingen from the real \`observer init\`
     registrars. -->

# SuperBased — plugins for AI coding agents

Install [SuperBased Observer](https://superbased.app/) from inside the AI
coding agent you already use. Observer is local-first token, cost and cache
observability: it captures what your coding agents actually do, and keeps it
in a SQLite database on your own machine.

**$PREREQ_SENTENCE** (\`npm i -g @superbased/observer\`, or
\`pipx install superbased-observer\`). Every artifact in this repository is
**wiring only** — each one declares an MCP server (and, for Claude Code,
lifecycle hooks) that runs a binary you install separately. Nothing here
downloads, bundles or installs a binary.

Plugin version: \`$VERSION\` — kept in lockstep with the observer release it
wires.

## What's in here

| Surface | Install artifact | Detail |
|---|---|---|
| Claude Code | \`.claude-plugin/marketplace.json\` + [\`$CLAUDE_PLUGIN_DIR/\`]($CLAUDE_PLUGIN_DIR/) | [$CLAUDE_PLUGIN_DIR/README.md]($CLAUDE_PLUGIN_DIR/README.md) |
| Codex | \`.agents/plugins/marketplace.json\` + [\`$CODEX_PLUGIN_PATH/\`]($CODEX_PLUGIN_PATH/) | [codex/README.md](codex/README.md) |
| Gemini CLI | [\`gemini-extension.json\`](gemini-extension.json) (repository root) | [gemini/README.md](gemini/README.md) |
| Goose | no manifest — Goose extensions *are* MCP servers | [goose/README.md](goose/README.md) |
| Cursor | a one-click \`cursor://\` deeplink | [cursor/README.md](cursor/README.md) |
| OpenCode | the \`$OPENCODE_PKG_NAME\` npm package | [opencode/README.md](opencode/README.md) |
| Kimi Code | [\`kimi.plugin.json\`](kimi.plugin.json) (repository root) | [kimi-code/README.md](kimi-code/README.md) |
| Qoder | \`.qoder-plugin/marketplace.json\` + [\`$QODER_PLUGIN_PATH/\`]($QODER_PLUGIN_PATH/) | [qoder/README.md](qoder/README.md) |
| Devin | \`.devin-plugin/plugin.json\` + \`mcp_config.json\` (repository root) | [devin/README.md](devin/README.md) |
| Droid | \`.factory-plugin/marketplace.json\` + [\`$DROID_PLUGIN_PATH/\`]($DROID_PLUGIN_PATH/) | [droid/README.md](droid/README.md) |
| OpenClaw | [\`openclaw.plugin.json\`](openclaw.plugin.json) (repository root) | [openclaw/README.md](openclaw/README.md) |
| Antigravity | [\`antigravity/$PLUGIN_DIR/\`](antigravity/$PLUGIN_DIR/) (copied or \`agy plugin install\`ed) | [antigravity/README.md](antigravity/README.md) |
| GitHub Copilot (VS Code) | a one-click \`vscode:mcp/install\` link | [copilot/README.md](copilot/README.md) |
| Claude Desktop / Cowork | [\`cowork/$PLUGIN_DIR/manifest.json\`](cowork/$PLUGIN_DIR/manifest.json) — an \`.mcpb\` bundle, **unverified** | [cowork/README.md](cowork/README.md) |
| Crush · Kiro CLI · Copilot CLI · Kilo Code · Roo Code · Open Interpreter · Command Code | a config block to paste (no package format exists) | see "Config listings" below |
| Pi | nothing — capture is native and Pi has no MCP client | [pi/README.md](pi/README.md) |

Two more tools reach this repository through a surface it already carries,
**per those vendors' own documentation** — we have not live-verified either,
and neither has an artifact of its own here:

- **Qwen Code** — \`qwen extensions install <owner>/<repo>\` is documented as
  auto-converting a \`gemini-extension.json\`, which is why that manifest sits
  at the repository root.
- **Grok** — \`docs.x.ai\` states Grok reads Claude Code marketplaces, plugins,
  MCPs and hooks with "zero configuration needed". Grok's own plugin schema is
  not publicly documented, so inventing a second manifest would be a guess; the
  Claude Code artifacts above are the Grok surface.

EOF

        printf '## Install\n\n'

        printf '### Claude Code\n\n'
        extract_section "$out/$CLAUDE_PLUGIN_DIR/README.md" "## Install" "## What it wires"
        printf 'Full detail: [%s/README.md](%s/README.md).\n\n' \
            "$CLAUDE_PLUGIN_DIR" "$CLAUDE_PLUGIN_DIR"

        printf '### Codex\n\n'
        extract_section "$out/codex/README.md" "## Install" "## What it wires"
        printf 'Full detail: [codex/README.md](codex/README.md).\n\n'

        printf '### Gemini CLI\n\n'
        extract_section "$out/gemini/README.md" "## Install" "## What it wires"
        printf 'In THIS repository that root-placement choice is already made: `gemini-extension.json`\n'
        printf 'sits at the top level, alongside the Claude Code and Codex catalogs.\n\n'
        printf 'Full detail: [gemini/README.md](gemini/README.md).\n\n'

        printf '### Goose\n\n'
        extract_section "$out/goose/README.md" \
            "## Install — the interactive way" "## Why there is no goose:// deeplink"
        printf 'Full detail: [goose/README.md](goose/README.md).\n\n'

        printf '### Cursor\n\n'
        extract_section "$out/cursor/README.md" "## The link" "## What the link encodes"
        printf 'Full detail — including the security constraint on deeplinks: [cursor/README.md](cursor/README.md).\n\n'

        printf '### OpenCode\n\n'
        extract_section "$out/opencode/README.md" "## Install" "## What it wires"
        printf 'Full detail: [opencode/README.md](opencode/README.md).\n\n'

        printf '### Kimi Code\n\n'
        extract_section "$out/kimi-code/README.md" "## Install" "## What it wires"
        printf 'Full detail: [kimi-code/README.md](kimi-code/README.md).\n\n'

        printf '### Qoder\n\n'
        extract_section "$out/qoder/README.md" "## Install" "## What it wires"
        printf 'Full detail: [qoder/README.md](qoder/README.md).\n\n'

        printf '### Devin\n\n'
        extract_section "$out/devin/README.md" "## Install" "## What it wires"
        printf 'Full detail: [devin/README.md](devin/README.md).\n\n'

        printf '### Droid\n\n'
        extract_section "$out/droid/README.md" "## Install" "## What it wires"
        printf 'Full detail: [droid/README.md](droid/README.md).\n\n'

        printf '### OpenClaw\n\n'
        extract_section "$out/openclaw/README.md" "## Install" "## What it wires"
        printf 'Full detail: [openclaw/README.md](openclaw/README.md).\n\n'

        printf '### Antigravity\n\n'
        extract_section "$out/antigravity/README.md" \
            "## Install" "## Why this plugin is NOT shipped at the repository root"
        printf 'Full detail — including why this one is NOT at the repository root: '
        printf '[antigravity/README.md](antigravity/README.md).\n\n'

        printf '### GitHub Copilot (VS Code)\n\n'
        extract_section "$out/copilot/README.md" "## Install" "## What the link encodes"
        printf 'Full detail: [copilot/README.md](copilot/README.md).\n\n'

        printf '### Claude Desktop / Cowork — UNVERIFIED\n\n'
        extract_section "$out/cowork/README.md" "## Install" "## Packing"
        printf 'Full detail — including what is unverified and why: '
        printf '[cowork/README.md](cowork/README.md).\n\n'

        cat <<EOF
## Config listings

Some tools have no plugin or extension package at all: their one
first-party extension surface is their own config file. For those, the
artifact is the exact block to paste — generated from the same registrars
as every manifest above, so a changed launch argument reaches it too.

| Tool | File | Detail |
|---|---|---|
| Crush | \`crush.json\`'s \`mcp\` key | [crush/README.md](crush/README.md) |
| Kiro CLI | \`~/.kiro/settings/mcp.json\` | [kiro-cli/README.md](kiro-cli/README.md) |
| GitHub Copilot CLI | \`~/.copilot/mcp-config.json\` (key \`mcpServers\`, **not** VS Code's \`servers\`) | [copilot-cli/README.md](copilot-cli/README.md) |
| Kilo Code | \`kilo.jsonc\`'s \`mcp\` key | [kilo-code/README.md](kilo-code/README.md) |
| Roo Code | \`.roo/mcp.json\` | [roo-code/README.md](roo-code/README.md) |
| Open Interpreter | \`~/.openinterpreter/config.toml\` | [open-interpreter/README.md](open-interpreter/README.md) |
| Command Code | \`~/.commandcode/mcp.json\` — though \`observer init\` writes this one for you | [command-code/README.md](command-code/README.md) |

And one tool needs nothing at all: **Pi** has no MCP client by design, and
observer already reads Pi's own session transcripts —
[pi/README.md](pi/README.md) explains what would and would not be worth
building there.

EOF

        cat <<EOF
## Why the layout looks like this

Every one of these formats resolves its relative paths from a **repository
root**, so all three root-level entry points have to sit at the top of this
repository. Their names do not collide, which is what lets one repository
serve all of them:

| Root path | Belongs to | Why it must be at the root |
|---|---|---|
| \`.claude-plugin/marketplace.json\` | Claude Code | the catalog entry's \`"./$CLAUDE_PLUGIN_DIR"\` source resolves against the directory holding \`.claude-plugin/\`; \`../\` is forbidden |
| \`.agents/plugins/marketplace.json\` | Codex | Codex reads a repo-scoped catalog at \`\$REPO_ROOT/.agents/plugins/marketplace.json\`, and the entry's \`"./$CODEX_PLUGIN_PATH"\` source resolves against that root |
| \`gemini-extension.json\` | Gemini CLI (and Qwen Code) | \`gemini extensions install\` documents a repository URL or a local path and nothing else — installing from a repository *subdirectory* is not documented |
| \`kimi.plugin.json\` | Kimi Code | \`/plugins install <github-url>\` installs a repository, so the manifest is the repository's |
| \`openclaw.plugin.json\` | OpenClaw | \`openclaw plugins install <git spec>\` likewise |
| \`.devin-plugin/plugin.json\` + \`mcp_config.json\` | Devin | \`devin plugins install owner/repo\` makes the repository root the plugin root, and Devin reads its components from that root |
| \`.factory-plugin/marketplace.json\` | Droid | \`droid plugin marketplace add <source>\` reads the catalog from the root — and Droid falls back to \`.claude-plugin/marketplace.json\` when it is absent, so shipping ours shadows that fallback with a plugin that declares only an MCP server. Its plugin lives at \`$DROID_PLUGIN_PATH/\` so it cannot merge with the Claude Code plugin directory |
| \`.qoder-plugin/marketplace.json\` | Qoder | \`qodercli plugins marketplace add <source>\` reads the catalog from the root, trying \`.qoder-plugin/marketplace.json\`, then \`.claude-plugin/marketplace.json\`, then \`marketplace.json\` — so without ours Qoder would install the Claude Code plugin, hooks and all. Only the catalog is at the root; the plugin it names stays at \`$QODER_PLUGIN_PATH/\`, which is also where Qoder's own documented local-path install points |

Everything else is in a subdirectory, because nothing about those tools
resolves from a repository root: the Qoder PLUGIN installs from a local
path (only its catalog needs the root, see above),
Antigravity stages a local directory into your own home (and deliberately
stays out of \`.agents/plugins/\`, which is Codex's), the Claude Desktop
bundle is packed rather than read in place, the Copilot link is a URI, and
the config listings are pages to read.

The per-surface READMEs below each install section were written against the
source tree, where every surface owns its own directory. Where one of them
draws a layout with a surface directory at the top (\`codex/\`, for example),
that directory **is this repository's root** here.

## How this repository is produced

**Generated:** every manifest (\`.claude-plugin/marketplace.json\`,
\`$CLAUDE_PLUGIN_DIR/.claude-plugin/plugin.json\`, \`.agents/plugins/marketplace.json\`,
\`$CODEX_PLUGIN_PATH/.codex-plugin/plugin.json\`, both \`.mcp.json\` files,
\`$CLAUDE_PLUGIN_DIR/hooks/hooks.json\`, \`gemini-extension.json\`), every
per-surface README, \`cursor/deeplink.txt\` and
\`opencode/src/wiring.generated.ts\`.

**Hand-written:** the OpenCode npm package's glue — \`opencode/package.json\`,
\`opencode/tsconfig.json\` and \`opencode/src/index.ts\` (the SDK plumbing a
generator has no business owning; the wiring it consumes is generated).
\`LICENSE\` is copied verbatim from the observer repository and
\`.gitignore\` is a fixed block in the assembler.

**Assembled:** this landing page. Its per-surface install sections are copied
verbatim out of the per-surface READMEs above, so an install command cannot
drift between this page and the surface that owns it.

The manifests are generated by
\`plugins/plugingen\` in the private \`superbased-observer\` repository, which
does not re-describe observer's wiring — it **runs the real \`observer init\`
registrars** against a throwaway sandbox \`HOME\` and transposes exactly what
they wrote into each surface's format. A changed MCP argument or a new hook
event therefore reaches these manifests automatically, and a CI drift gate
fails until the regenerated tree is committed.

This repository tree is then assembled from that output by
\`scripts/assemble-plugins-repo.sh\`, which performs the
directory-per-surface → repository-root transpose described above and stamps
the release version.

The one deliberate deviation from what \`observer init\` writes: init
registers the **absolute path** of the running binary, which a cache-copied
plugin cannot know, so every manifest here resolves \`observer\` from \`PATH\`.

## Honesty notes

- **Wiring only.** $PREREQ_SENTENCE. No artifact here ships, downloads or
  bundles a binary, and each listing says so in those words.
- **Local by default.** Captured data lands in \`~/.observer/observer.db\`.
  The MCP server makes no network calls of its own; shipping anything off the
  machine is a separate, opt-in Teams configuration none of these plugins
  touch.
- **No efficiency claims.** No listing here promises an efficiency, context
  or cost benefit of any kind. Observer measures what your agents spend; it
  does not claim to change it.
- **Double-wiring.** Several of these surfaces declare the same MCP server
  \`observer init\` writes into that tool's own config. Where a duplicate is
  possible, the surface's README says so plainly and tells you what to do
  about it. Claude Code is the one surface where \`observer init\` detects the
  plugin and stands down by itself.

## License

Apache-2.0 — see [LICENSE](LICENSE).
EOF
    } > "$readme"
}

# ---------------------------------------------------------------------
# honesty_gate — the assembly-time half of plugingen's listing gate.
# ---------------------------------------------------------------------

honesty_gate() {
    local out="$1"

    # (a) + (c) THE shared checker, in Go, over EVERY file of the final
    #     assembled tree: no savings claim (literal phrases AND the
    #     %-near-efficiency-vocabulary pattern class), and the verbatim
    #     prerequisite sentence in every README — including the root
    #     landing page this script authors. One owner:
    #     plugins/plugingen/honesty.go, which plugingen's own tests run
    #     over the generated tree.
    command -v go >/dev/null 2>&1 \
        || die "the honesty gate needs the Go toolchain (it runs plugins/plugingen -honesty-check, the one owner of the rule)"
    (cd "$REPO_ROOT" && go run ./plugins/plugingen -honesty-check "$out") \
        || die "the assembled tree failed the honesty gate (see above)"

    # (b) Every manifest description that exists carries it too. Gemini's
    #     manifest has no description field (the documented schema has
    #     none), which is why its README states it instead.
    local manifest
    for manifest in \
        "$out/.claude-plugin/marketplace.json" \
        "$out/$CLAUDE_PLUGIN_DIR/.claude-plugin/plugin.json" \
        "$out/$CODEX_PLUGIN_PATH/.codex-plugin/plugin.json" \
        "$out/opencode/package.json" \
        "$out/kimi.plugin.json" \
        "$out/openclaw.plugin.json" \
        "$out/.devin-plugin/plugin.json" \
        "$out/.factory-plugin/marketplace.json" \
        "$out/$DROID_PLUGIN_PATH/.factory-plugin/plugin.json" \
        "$out/.qoder-plugin/marketplace.json" \
        "$out/$QODER_PLUGIN_PATH/.qoder-plugin/plugin.json" \
        "$out/cowork/$PLUGIN_DIR/manifest.json"
    do
        node - "$manifest" "$PREREQ_SENTENCE" <<'EOF'
const fs = require('fs');
const [, , filePath, sentence] = process.argv;
const doc = JSON.parse(fs.readFileSync(filePath, 'utf8'));
// A CATALOG (anything with a plugins array) describes the marketplace
// itself at the top level — that line is a shelf label, not a listing, so
// only its ENTRY descriptions are gated. Everything else is a single
// listing and its own description is what a user reads.
const descriptions = [];
if (Array.isArray(doc.plugins)) {
  for (const entry of doc.plugins) {
    if (typeof entry.description === 'string') descriptions.push(entry.description);
  }
} else if (typeof doc.description === 'string') {
  descriptions.push(doc.description);
}
if (descriptions.length === 0) {
  console.error(`${filePath}: no description to gate`);
  process.exit(1);
}
for (const d of descriptions) {
  if (!d.includes(sentence)) {
    console.error(`${filePath}: a description does not state the binary prerequisite verbatim:\n  ${d}`);
    process.exit(1);
  }
}
EOF
    done

}

# ---------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------

if [ "$SELF_CHECK" -eq 1 ]; then
    assert_source_completeness
    a=$(mktemp -d)
    b=$(mktemp -d)
    trap 'rm -rf "$a" "$b"' EXIT
    rmdir "$a" "$b"
    assemble "$a"
    assemble "$b"
    if ! diff -r "$a" "$b"; then
        die "assembly is NOT deterministic — two runs produced different trees"
    fi
    if [ "$VERSION" = "$SELF_CHECK_FIXTURE_VERSION" ]; then
        echo "assemble-plugins-repo: deterministic — two runs at $VERSION (FIXTURE version; --self-check publishes nothing, pass a real tag to assemble a release) are byte-identical"
    else
        echo "assemble-plugins-repo: deterministic — two runs at $VERSION are byte-identical"
    fi
    echo "assemble-plugins-repo: $(find "$a" -type f | wc -l) files, honesty gate passed"
    exit 0
fi

assemble "$OUT_DIR"

echo "assemble-plugins-repo: assembled the superbasedapp/plugins tree at $VERSION"
echo
(cd "$OUT_DIR" && find . -type f | sort | sed 's|^\./|  |')
echo
echo "  Claude Code : /plugin marketplace add superbasedapp/plugins"
echo "  Codex       : codex plugin marketplace add superbasedapp/plugins"
echo "  Gemini CLI  : gemini extensions install https://github.com/superbasedapp/plugins"
echo
echo "NOTHING WAS PUBLISHED. This script writes one directory and nothing else."
