#!/usr/bin/env bash
# verify-website-build.sh — assert every committed top-level marketing page
# under website/ matches a fresh render of website/pages-src/.
#
# Unlike `make website-build`, this NEVER mutates the working tree: it renders
# into a temp dir and diffs. A hand-edit to a rendered page (instead of its
# source) therefore fails loudly here rather than being silently overwritten
# by the next build.
#
# This is the gate that keeps the shared chrome shared. Before the shell
# existed the site had accumulated four distinct #topnav variants, three
# distinct footer variants, missing data-track attributes and stale build
# markers — all from hand-edited copy-pasted chrome.
#
# Mirrors scripts/verify-distribution-readmes.sh.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

SRC_DIR="website/pages-src"
SITE_DIR="website"

if [ ! -d "$SRC_DIR" ]; then
    echo "verify-website-build: missing $SRC_DIR" >&2
    exit 1
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# The generator resolves -src/-out relative to its own working directory
# (website/docs-tools), matching how `make docs-build` invokes its sibling.
(cd website/docs-tools && go run ./pagegen -src "../pages-src" -out "$tmpdir") \
    || { echo "verify-website-build: pagegen failed" >&2; exit 1; }

fail=0

# --- Direction 1: every page the generator PRODUCES is committed, byte-identical.
while IFS= read -r rendered; do
    rel="${rendered#"$tmpdir"/}"
    committed="$SITE_DIR/$rel"
    if [ ! -f "$committed" ]; then
        echo "verify-website-build: $committed missing (pages-src renders it)" >&2
        fail=1
        continue
    fi
    if ! diff -u "$committed" "$rendered" > "$tmpdir/.diff"; then
        echo "verify-website-build: $committed drifted from $SRC_DIR"
        echo "----- diff: committed (a) vs rebuilt (b) -----"
        cat "$tmpdir/.diff"
        echo "-----"
        fail=1
    fi
done < <(find "$tmpdir" -type f -name '*.html' | sort)

# --- Direction 2: every committed page that CLAIMS to be pagegen output is one
# the generator still produces (i.e. it still has a source).
#
# Direction 1 alone enumerates only what the generator emitted, so it is blind
# to ORPHANS: delete website/pages-src/about.html but keep (and hand-edit)
# website/about.html and the loop above renders 8 pages, visits 8, and never
# looks at about.html at all. The gate passes while an unowned, hand-edited
# page ships.
#
# The owned set is DERIVED, never hardcoded: pagegen stamps every file it
# writes with the banner below (see pagegen/shell.html.tmpl), and the check is
# simply "signed ⊆ produced". So it stays correct when a page is added,
# renamed or given a different `out`, and it does not touch the site's
# hand-maintained HTML — arcade.html, 404.html, legal/*.html, deck/** and all
# of docs/** (rendered by the SIBLING generator `gen`) carry no pagegen banner.
PAGEGEN_MARKER='GENERATED by website/docs-tools/pagegen'
while IFS= read -r committed; do
    rel="${committed#"$SITE_DIR"/}"
    if [ ! -f "$tmpdir/$rel" ]; then
        echo "verify-website-build: $committed is stamped as pagegen output but $SRC_DIR renders no such page" >&2
        echo "  -> its source was deleted or its front-matter 'out' changed; delete the orphan or restore the source" >&2
        fail=1
    fi
done < <(grep -rlF "$PAGEGEN_MARKER" "$SITE_DIR" --include='*.html' \
    --exclude-dir=node_modules --exclude-dir=pages-src 2>/dev/null | sort)

if [ "$fail" != "0" ]; then
    echo "marketing-page drift detected; edit website/pages-src/, run 'make website-build', and commit" >&2
    exit 1
fi

echo "marketing pages: in sync with $SRC_DIR"
